### ISSUE TITLE
ide-plugin.js problem exporting a Test Suite

### ISSUE THREAD

**Issue by ramjr2012** [teodesian/Selenium-Remote-Driver#168]
After installing the plugin, two new menu items are listed in the "File" meneu:  "Export Test Case as ..." and "Export Test Suite as ...".
Exporting individual test cases works fine, producing valid code.
Exporting the test _suite_ produces Ruby code rather than Perl code.  Specifically, it produces the same code that is created by the "Ruby / RSpec / WebDriver" menu element.
I don't know if this is an issue with the plugin javascript, a problem with the Selenium plugin itself, or with me ;)  I would tend to think this is some sort of enumeration issue in Selenium.  If you agree, I can close this and submit it there.  If it's me, I'd like to know what I'm doing wrong ;)
I'm using Selenium 2.8.0 and S.R.D 0.2150
Thanks.

**Comment by Hipska** [comment]
This formatter has some bugs and unimplemented features. I would like to make changes and update it, but I cannot find any documentation for this. Does anybody have a clue? Or does one know about a better formatter to use for this perl module?

**Comment by gempesaw** [comment]
Yeah unfortunately I can't be of much assistance on either front - using our formatter, or if a better formatter exists. I know from a high level what the plugin is supposed to do, but I've only glanced at the code a few times and I don't use it, so. =/

**Comment by Hipska** [comment]
Thanks for your quick response! Unfortunately, finding documentation for Selenium is really hard.

**Comment by peroumal1** [comment]
For what it worth, I used this plugin once, and the result was quite useless : 
  * it is way outdated regarding the current state of Selenium::Remote::Driver (I guess it was written for Selenium RC ?)
  * it is buggy 
  * it does not support any of the extensions you can add to Selenium IDE in Firefox

This means that most of the time, if you ever use this, you will have to work as twice as much as if you tried to write the Perl code directly... so you should try to write Perl code directly.
On the bright side, if any question regarding Selenium::Remote::Drive, we are able to help ;) 

@gempesaw maybe we should remove the .js file ?

**Comment by Hipska** [comment]
@peroumal1 All of your points could possibly be fixed by updating the ide-plugin.js, therefore I would not recommend removing it. I would put a comment/warning at the top of the file that it is way out dated.

**Comment by teodesian** [comment]
I remember using the selenium recorder ide maybe 5 years ago?  Biggest problem is that it's useless at modern web pages with DOM changing from XHRs -- race conditions galore.  Pretty much a recipe for flaky, unreliable tests which is why nobody at our organization uses it at all anymore.

The templater would need significant re-work to produce S::R::D commands waiting on most every element given the new reality of the web.  I have no interest in doing this anytime soon, but it shouldn't be too difficult if the requisite waiter convenience subs and error handlers are in place.

**Comment by teodesian** [comment]
I whacked the file since this isn't getting fixed any time ever.
