### ISSUE TITLE
Selenium/Remote/RemoteConnection.pm Error

### ISSUE THREAD

**Issue by tranwave** [teodesian/Selenium-Remote-Driver#232]
I noticed when a selenium server gets overloaded it these errors happen in the API (using 0.17). 

Use of uninitialized value in string eq at Selenium/Remote/RemoteConnection.pm line 35, <DATA> line 1853.
Use of uninitialized value in string ne at Selenium/Remote/RemoteConnection.pm line 30, <DATA> line 1853.

Does this error happen on the connection $var = new Selenium::Remote::Driver(args). I have this connection code encapsulated in try catch blocks but it still prints out the error to the console. Does this error also get placed in $_ in the catch block as well as printing it out to the screen?

**Comment by teodesian** [comment]
I have a patch for this somewhere, this was just unhandled data.  Wrapping it with guards seemed to have no ill effects, so I'll look at bringing this in, supposing this still happens -- I haven't seen it in a while myself.
