### ISSUE TITLE
find_element_ok() and friends should return the found element

### ISSUE THREAD

**Issue by makholm** [teodesian/Selenium-Remote-Driver#257]
Or at least it could. :-)

A lot of web driver test code is just finding elements and clicking on them. It seems like `find_element_ok()` would be more useful and make for less boilerplate in tests if it would return the found element (which is always true anyway). E.g.:

```
my $this = $driver->find_element_ok('#the-button');
$this->click_ok();
```

Instead of the more verbose:

```
ok my $this = $driver->find_element('#the-button'), 'found #the-button';
# + even more code for exception handling etc...
$this->click_ok();
```

Before I discovered `Test::Selenium::Remote::Driver`, I was half way through my own test lib around the driver that had something like:

```
sub find_element_ok {
    my ($self, $selector, @selector_kind) = @_;
    my ($ex, $el);
    try { $el = $self->find_element($selector, @selector_kind) } catch { $ex = $_ };
    ok $el, "find_element $selector" or diag $ex;
    return $el;
}
```

Most of the time I don't even care that much about exception handling. I just want a `find_element()` that will tell me the selector so I can track progress and track where tests failurs.

Thoughts?

**Comment by gempesaw** [comment]
oh yeah that seems to be pretty useful at first blush.

hmm, what would happen for `find_elements_ok`? oh and then the behavior is different from what gets returned by `find_no_element(s)_ok`, hmm. perhaps a bit more complicated than I thought.

**Comment by teodesian** [comment]
Well, as long as the finder returns undef/false this would probably work, unless any of the objects are bless(0,'Selenium::Remote::Driver') or something like that.  I don't think it is the case, so this should be do-able.

That said, the behavior for find_elements_ok and find_no_elements_ok should be fine as long as they return ARRAY, given empty arrays evaluate as false.

**Comment by teodesian** [comment]
not worth it

Just do `my $lem = $driver->find_element(...); ok( $lem->isa ...)`
