### ISSUE TITLE
Selenium::Firefox does not clean up geckodriver process

### ISSUE THREAD

**Issue by vkatsikaros** [teodesian/Selenium-Remote-Driver#280]
I have a problem running Firefox 48 and 49 with both geckodriver 0.9 and 0.10:
- 0.9: firefox can't be launched
- 0.10: there are leftover geckodriver process

Let me know if I can provide any more info or if I can assist somehow.
## My env

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:    14.04
Codename:   trusty

$ perl -v

This is perl 5, version 18, subversion 2 (v5.18.2) built for x86_64-linux-gnu-thread-multi
(with 44 registered patches, see perl -V for more detail)

$ perl -MSelenium::Remote::Driver -e 'print $Selenium::Remote::Driver::VERSION';
1.00
```

I tried with both 

```
$ /usr/bin/firefox -version
Mozilla Firefox 48.0 # from https://launchpad.net/~ubuntu-mozilla-security/+archive/ubuntu/ppa/+build/10532218/+files/firefox_48.0+build2-0ubuntu0.14.04.1_amd64.deb
# and
$ /usr/bin/firefox -version
Mozilla Firefox 49.0
```
## Test script

I am using the following test script

```
#!/usr/bin/perl
use strict;
use warnings;
use Selenium::Firefox;

$ENV{ 'DISPLAY' } = 'vkcloud2:1';
my $driver = Selenium::Firefox->new();
$driver->get( 'http://www.google.com/' );
$driver->capture_screenshot( 'screenshot.png' );
sleep(5); # just enough to capture netstat output
# I used a) only quit b) only shutdown_binary c) quit followed by shutdown_binary
# but the result was the same in all 3 cases
$driver->quit();
$driver->shutdown_binary();
```
## With geckodriver 0.10.0 (Aug 3)

This version has the note 

> Only upgrade to this version if you are using Selenium 3 beta releases.

but I tried it anyway

The 1st time I run it I get

```
# before running the script 1st time
$ netstat -tlp | egrep '(firefo|vnc|gecko)'
tcp        0      0 localhost:5901          *:*                     LISTEN      11871/Xvnc4     
tcp        0      0 *:x11-1                 *:*                     LISTEN      11871/Xvnc4    
# while it's running
$ netstat -tlp | egrep '(firefo|vnc|gecko)'
tcp        0      0 localhost:9090          *:*                     LISTEN      11970/geckodriver
tcp        0      0 localhost:2828          *:*                     LISTEN      11976/firefox   
tcp        0      0 localhost:5901          *:*                     LISTEN      11871/Xvnc4     
tcp        0      0 *:x11-1                 *:*                     LISTEN      11871/Xvnc4     
# after it exited
$ netstat -tlp | egrep '(firefo|vnc|gecko)'
tcp        0      0 localhost:9090          *:*                     LISTEN      11970/geckodriver
tcp        0      0 localhost:5901          *:*                     LISTEN      11871/Xvnc4     
tcp        0      0 *:x11-1                 *:*                     LISTEN      11871/Xvnc4    
```

I wait a bit and then I run it for the 2nd time

```
# before running the script 2nd time
$ netstat -tlp | egrep '(firefo|vnc|gecko)'
tcp        0      0 localhost:9090          *:*                     LISTEN      11970/geckodriver
tcp        0      0 localhost:5901          *:*                     LISTEN      11871/Xvnc4     
tcp        0      0 *:x11-1                 *:*                     LISTEN      11871/Xvnc4     
# while it's running
$ netstat -tlp | egrep '(firefo|vnc|gecko)'
tcp        0      0 localhost:9090          *:*                     LISTEN      11970/geckodriver
tcp        0      0 localhost:9091          *:*                     LISTEN      12490/geckodriver
tcp        0      0 localhost:2828          *:*                     LISTEN      12498/firefox   
tcp        0      0 localhost:5901          *:*                     LISTEN      11871/Xvnc4     
tcp        0      0 *:x11-1                 *:*                     LISTEN      11871/Xvnc4     
$ netstat -tlp | egrep '(firefo|vnc|gecko)'
# after it exited
tcp        0      0 localhost:9090          *:*                     LISTEN      11970/geckodriver
tcp        0      0 localhost:9091          *:*                     LISTEN      12490/geckodriver
tcp        0      0 localhost:5901          *:*                     LISTEN      11871/Xvnc4     
tcp        0      0 *:x11-1                 *:*                     LISTEN      11871/Xvnc4     
```

Notice the two geckodriver instances at ports 9090, 9091.
## With geckodriver 0.9.0 (Jun 30)

```
$ perl  test_firefox.pl 
Unable to connect to the /usr/local/bin/geckodriver binary on port 9090 at /usr/local/share/perl/5.18.2/Selenium/CanStartBinary.pm line 168.
```
## make & test outputs

They don't reproduce the problem mentioned but they aren't passing either, so I though I should mention.

```
# this might be unrelated
$ perl Makefile.PL
Warning: prerequisite Moo 1.005 not found. We have 1.004002.

# set env variables
$ export DISPLAY='vkcloud2:1'
$ export RELEASE_TESTING='1'

$ /usr/local/bin/geckodriver --version
geckodriver v0.9.0

$ perl t/CanStartBinary.t 
ok 1 # skip Phantomjs binary not found in path
ok 2 # skip Phantomjs binary not found in path
ok 3 # skip Phantomjs binary not found in path
ok 4 - we throw if the user specified binary is not executable
ok 5 # skip PhantomJS needed for manual binary path tests
ok 6 # skip PhantomJS needed for manual binary path tests
ok 7 # skip Chrome binary not found in path
ok 8 # skip Chrome binary not found in path
ok 9 # skip Chrome binary not found in path
Unable to connect to the /usr/local/bin/geckodriver binary on port 9090 at /usr/local/share/perl/5.18.2/Selenium/CanStartBinary.pm line 168.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 111 just after 9.

$ /usr/local/bin/geckodriver --version
geckodriver 0.10.0

$ perl t/CanStartBinary.t 
ok 1 # skip Phantomjs binary not found in path
ok 2 # skip Phantomjs binary not found in path
ok 3 # skip Phantomjs binary not found in path
ok 4 - we throw if the user specified binary is not executable
ok 5 # skip PhantomJS needed for manual binary path tests
ok 6 # skip PhantomJS needed for manual binary path tests
ok 7 # skip Chrome binary not found in path
ok 8 # skip Chrome binary not found in path
ok 9 # skip Chrome binary not found in path
Use of uninitialized value in hash element at /usr/local/share/perl/5.18.2/Selenium/Remote/ErrorHandler.pm line 126.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 9.
```

**Comment by vkatsikaros** [comment]
I tried it with FF 48 and got the same result (I updated my comment above)

**Comment by gempesaw** [comment]
Ooh, thanks for putting all that information together. Seems like a bit of a mystery, let's see... What happens when you:

- execute geckodriver manually like `geckodriver -vv` and then do a `curl -X POST localhost:4444/session --data {}` ? Any chance those logs give a helpful error message?
- start sel3-beta4 like `java -jar -Dwebdriver.gecko.driver=/path/to/your/geckodriver selenium-standalone-server-3.0.0-beta4.jar` and then do `curl -X POST localhost:4444/wd/hub/session --data '{"desiredCapabilities":{"browserName":"firefox"}}'` ? Same question about the standalone server logs, or the JSON response to the curl - any helpful error messages in there?

**Comment by vkatsikaros** [comment]
Thanks for prompt answer and the guidance. I'll start with the first request (`geckodriver -vv`) as I am not experienced with the selenium server and will need to do a bit of work to set it up.

I first tried
```
curl -X POST localhost:4444/session --data {}
```

In both FF 48 and 49, with both geckodriver 0.9 and 0.10, an FF gets up and running and I get an response from the curl's session.

For more details:
geckodriver, FF, output
0.10,  48,  https://gist.github.com/vkatsikaros/63305a603453d011a09a43a34f2b6e75#file-0-10_48-md
0.9,  48, https://gist.github.com/vkatsikaros/63305a603453d011a09a43a34f2b6e75#file-0-9_48-md
0.10, 49, https://gist.github.com/vkatsikaros/63305a603453d011a09a43a34f2b6e75#file-0-10_49-md
0.9, 49, https://gist.github.com/vkatsikaros/63305a603453d011a09a43a34f2b6e75#file-0-9_49-md

So, regarding the problem  the script has with geckodriver 0.9 not launching at all (both firefox 48 & 49) I could  **not** reproduce the problem. 


Regarding the problem the script has with 0.10 the leftover geckodriver processes, I tried to replicate it by modifying the above curl with 
```
curl -s -X DELETE localhost:4444/session/`curl -s -X POST localhost:4444/session --data {} | sed 's/.*"sessionId":"\(.*\)","value":.*/\1/'` --data {}
```
Firefox gets up as before, but geckodrvier doesn't terminate in any case. But maybe `DELETE 	/session/{sessionId}` isn't the full story to cleanly quiting.

Let me know if you need any more info (before venturing to test with the selenium server), and if you want me to proceed with the selenium server.

**Comment by vkatsikaros** [comment]
I have narrowed down the problem a bit.

Summary
---------
It seems that `geckodriver` doesn't shut down via an HTTP command, like Selenium::CanStartBinary->shutdown_binary expects, so we have to kill it to ensure geckodriver is terminated.

Details
---------
The original problem was: with geckodriver 0.9: firefox can't be launched. But let's _forget_ this case for a bit, since 2 newer versions have appeared.

So we are left with the problem 0.10: there are leftover geckodriver process.

Geckodriver doesn't exit when the session is DELETEed. [I've asked about this](http://logs.glob.uno/?c=mozilla%23ateam&s=7+Oct+2016&e=7+Oct+2016#c1075410) in the `#ateam` mozilla IRC channel So one has to explicitly shuti it down

Selenium::Firefox documentation warns us to use `shutdown_binary`. Now, if I read it correctly, `shutdown_binary` will send an HTTP command to the binary [to shut it down](https://github.com/gempesaw/Selenium-Remote-Driver/blob/master/lib/Selenium/CanStartBinary.pm#L357). But it seems geckodriver can't be shut down like that.

I tested with curl
```
$ curl http://127.0.0.1:4444/wd/hub/shutdown
{"error":"unknown command","message":"GET /wd/hub/shutdown did not match a known command"}
```

And then tested that with a script, to see if this GET command is indeed sent:
```
my $driver = Selenium::Firefox->new();
$driver->shutdown_binary();
```
and got from ` tcpdump -nnvvXSs 1514 -i any dst 127.0.0.1 and port 9090`:
```
    127.0.0.1.9090 > 127.0.0.1.41036: Flags [P.], cksum 0xff08 (incorrect -> 0xffda), seq 3098564509:3098564733, ack 4220638080, win 175, options [nop,nop,TS val 128102750 ecr 128102750], length 224
	0x0000:  4500 0114 e6c4 4000 4006 551d 7f00 0001  E.....@.@.U.....
	0x0010:  7f00 0001 2382 a04c b8b0 579d fb91 d380  ....#..L..W.....
	0x0020:  8018 00af ff08 0000 0101 080a 07a2 b15e  ...............^
	0x0030:  07a2 b15e 4854 5450 2f31 2e31 2034 3034  ...^HTTP/1.1.404
	0x0040:  204e 6f74 2046 6f75 6e64 0d0a 436f 6e6e  .Not.Found..Conn
	0x0050:  6563 7469 6f6e 3a20 636c 6f73 650d 0a44  ection:.close..D
	0x0060:  6174 653a 2054 6875 2c20 3133 204f 6374  ate:.Thu,.13.Oct
	0x0070:  2032 3031 3620 3134 3a33 333a 3330 2047  .2016.14:33:30.G
	0x0080:  4d54 0d0a 436f 6e74 656e 742d 4c65 6e67  MT..Content-Leng
	0x0090:  7468 3a20 3930 0d0a 436f 6e74 656e 742d  th:.90..Content-
	0x00a0:  5479 7065 3a20 6170 706c 6963 6174 696f  Type:.applicatio
	0x00b0:  6e2f 6a73 6f6e 0d0a 0d0a 7b22 6572 726f  n/json....{"erro
	0x00c0:  7222 3a22 756e 6b6e 6f77 6e20 636f 6d6d  r":"unknown.comm
	0x00d0:  616e 6422 2c22 6d65 7373 6167 6522 3a22  and","message":"
	0x00e0:  4745 5420 2f77 642f 6875 622f 7368 7574  GET./wd/hub/shut
	0x00f0:  646f 776e 2064 6964 206e 6f74 206d 6174  down.did.not.mat
	0x0100:  6368 2061 206b 6e6f 776e 2063 6f6d 6d61  ch.a.known.comma
	0x0110:  6e64 227d                                nd"}
```

**Comment by gempesaw** [comment]
man, awesome, thanks for querying about the shutdown stuff in the IRC channel. good to have confirmation. It completely slipped my mind to check for the `geckodriver` processes hanging around afterwards, but yeah this is definitely a bug that should get resolved asap.

agreed about 0.9 btw, I'm happy to go punt on older version compatibility.

**Comment by vkatsikaros** [comment]
Thanks! I can see this be solved with fork the binary and killing it from the parent when terminating. But I am uncertain how/if this affects:
- portability
- the other binary browsers
I have started working on a patch for the above solution and will probably have it ready today. 

PS No worries if you have a solution already, it will be a good Moo exercise and SRD code digging anyway :)

**Comment by gempesaw** [comment]
That sounds like a good approach. I don't have a solution at the ready, so it's much appreciated! c: I have a windows box available that I can try to verify portability with, as well.

**Comment by vkatsikaros** [comment]
RE https://github.com/gempesaw/Selenium-Remote-Driver/pull/289 I'd be happy to do more coding and/or tests. I'd also be happy to code alternatives if the change looks too pervasive (but I'll might some directions).

Hope it looks useful.

**Comment by vkatsikaros** [comment]
For sanity I tested https://github.com/gempesaw/Selenium-Remote-Driver/pull/289 with geckodriver 0.11.0 and firefox 49; it works as expected. 

- Without the fork, the geckodriver process remains afterwards
- With the fork, SRD works (executes successfully webdriver commands) and the geckodriver process goes away afterwards.

**Comment by teodesian** [comment]
OK, I'm gonna take this and get it to work, as I'm finally in a place where I need this to work.
