### ISSUE TITLE
Remove croak in find_element_by_*

### ISSUE THREAD

**Issue by ylavoie** [teodesian/Selenium-Remote-Driver#320]
Those are there to validate if an element is present and expect it might not be.
The driver should not croak on error but only return zero.

**Comment by teodesian** [comment]
I agree.  Code used for testing as heavily as selenium should only halt execution in the most extreme of circumstances.  I will look at this.

**Comment by teodesian** [comment]
That said, in the meantime, look at Test::Exception.

**Comment by ylavoie** [comment]
Already did, thanks. It brings other problems with our application.

**Comment by DrJHD** [comment]
A workaround:

    use strict; use warnings;
    use Test::More;
    use Selenium::Chrome;

    my $url    = 'http://www.perlmonks.org';
    my $driver = Selenium::Chrome->new();
    $driver->get($url);
    my $errcroak = eval {
        my $eltcroak = $driver->
            find_element('Cthulhu', 'id');
        1};
    ok $errcroak, "Test should croak";
    print $@ unless $errcroak;
    $errcroak = eval {
        my $eltcroak = $driver->
            find_element('Voting_Booth', 'id');
        1};
    ok $errcroak, "Test should NOT croak";
    print $@ unless $errcroak;
    $driver->quit();
    done_testing;

Code taken from https://www.amazon.com/dp/B07D5VQR98/ - code examples downloadable from https://perlschool.com/books/selenium-perl/. This one is ChrErrEval.pl.

**Comment by teodesian** [comment]
These already don't throw per the documentation.

See Selenium::Remote::Finders.pm -- that's what implements these find_element_by_* aliases.

This is actually an invalid bug.
