### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by fecundf** [teodesian/Selenium-Remote-Driver#322]
I'd like to see Safari support! I took a stab at implementing "Selenium::Safari" by modifying "Selenium::Chrome" and looking at the python code in selenium/webdriver/safari/webdriver.py (which works for me) and got a few steps in, but not enough to have anything functional.

Here's what I found:

Replacing "chrome" with "safari" globally was a great first step

Safari's webdriver has no "/wd/hub" prefix, adding this to Selenium/Safari.pm helped:

```
has wd_context_prefix => (
	is => 'ro',
	default => ''
  );
```

The binary is called 'safaridriver,' its default port is 4444, and that's the only arg one can pass to safaridriver.

The Python library creates a connection before it runs "check_status," and I think Safari's driver doesn't return anything until it has a connection POSTed. This is where I got lost.

Falling back to using Chrome for my testing at the moment, it's close enough. If I can help with testing a Safari module let me know and I will.

**Comment by teodesian** [comment]
So, I've at least made sure that using safari through the selenium server works; that should be in the 1.21 release (coming soon).

That said, the 'no server' implementation will have to wait a bit - - to be fair, all the other ones are probably broken currently anyhow.

**Comment by teodesian** [comment]
#361 will do the latter half of this.
