### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by gempesaw** [teodesian/Selenium-Remote-Driver#324]
Hullo, 

I am looking for a maintainer to transfer this project to as S::R::D and Perl aren't my top priority anymore. I'd like to transfer this Github repo and assign the Pause permissions for the S::R::D namespace. (If you're a new programmer and you're interested in stepping up but worried this might be too much, please reach out! I'm more than happy to help as needed)

The project is built with Dist::Zilla, so it'd be helpful to know, but it's not really a huge deal if you're unfamiliar with it, as `dzil` is pretty straightforward. Testing & the server mocks have gotten less convoluted and are significantly easier to update thanks to @peroumal1. The main maintenance tasks these days are actually keeping up to date with the W3C spec in the form of geckodriver bugs that come through where S::R::D isn't spec-compliant (since the webdriver 2.0 & 3.0 servers weren't/aren't 100% spec compliant either). 

I think I'm planning to work on #322, and I'd like to continue pitching in when I can, but overall I should think there are plenty of people who have S::R::D as a higher priority than I can find time for. Cheers!

**Comment by teodesian** [comment]
I'll do it.  TEODESIAN on CPAN.

Our firm has several hundred webdriver intensive tests, so it would behoove us to have someone keeping things up.

I'm familiar with DZIL and the codebase (have already written patches), so it should be a decent fit.

**Comment by gempesaw** [comment]
Great! I transferred the pause permissions already, but I can't transfer the Github repo to you, presumably because you have a fork and it's the same name and I guess Github doesn't know what to do in that case...

**Comment by teodesian** [comment]
I guess that's fine?  I'll update the Repo location in dist.ini with the next release.  After that I suppose you can turn off new issues and I'll migrate the stragglers to my fork.

**Comment by teodesian** [comment]
Actually, I just deleted my fork.  See if it will work now @gempesaw

**Comment by gempesaw** [comment]
Okay, I put in a transfer request through the Github UI and ... perhaps it's waiting on you to do something ?

**Comment by teodesian** [comment]
Had to accept it via email apparently.  The gears seem to be in motion now

**Comment by teodesian** [comment]
Looks like it worked.  Time to update Readme.MD

**Comment by teodesian** [comment]
OK.  Thanks Daniel.  I'm will triage issues later tonight.

**Comment by troglodyne** [comment]
Looks like you probably should update the Travis CI stuff too, currently it shows build status of 'unknown'. on the README page, likely due to changeover of the repo.

**Comment by teodesian** [comment]
fixed in fc6013eb69fe9993b9aea7ec73a06af8c3f7753e

**Comment by teodesian** [comment]
Also working on testing on more perls and setting up coveralls.io

**Comment by teodesian** [comment]
done in c291a8a1d1aa8a039fc659755033284df32f3bb5
