### ISSUE TITLE
sendModifier: An unknown server-side error

### ISSUE THREAD

**Issue by spencebah** [teodesian/Selenium-Remote-Driver#326]
Selenium::Remote::Driver returns an error when attempting to call send_modifier().

&nbsp;

Environment:
* Ubuntu 16.04
* Selenium Server v2.45.0
* Firefox 35.0.1

&nbsp;

We're trying to capture the contents of the clipboard by setting up a js listener, and then sending 'Ctrl+V'

    my $input_field = $driver->find_element( 'input', 'id' );
    $driver->send_modifier( 'Ctrl', 'down' );
    $input_field->send_keys('v');
    $driver->send_modifier( 'Ctrl', 'up' );

&nbsp;

This results in an error on the first send_modifier() call:

    Error while executing command: sendModifier: An unknown server-side error occurred while processing the command.: POST /session/9b27bea7-a55f-45b3-8874-7d7e3cfd605f/modifier
    Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
    System info: host: 'selenium.head', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-64-generic', java.version: '1.8.0_121'
    Driver info: driver.version: unknown at /usr/local/${CustomLib}/Try/Tiny.pm line 98.
     at /usr/local/${CustomLib}/Driver.pm line 68.
        ${CustomLib}::Driver::__ANON__(${CustomLib}::Driver=HASH(0x4ce3c70), "Error while executing command: sendModifier: An unknown serve"...) called at /usr/local/${CustomLib}/Selenium/Remote/Driver.pm line 308
        Selenium::Remote::Driver::__ANON__("Error while executing command: sendModifier: An unknown serve"...) called at /usr/local/${CustomLib}/Try/Tiny.pm line 119
        Try::Tiny::try(CODE(0x56d9f70), Try::Tiny::Catch=REF(0x56da4e0)) called at /usr/local/${CustomLib}/Selenium/Remote/Driver.pm line 313
        Selenium::Remote::Driver::__ANON__(CODE(0x420dca0), ${CustomLib}::Driver=HASH(0x4ce3c70), HASH(0x52761a0), HASH(0x4f88018)) called at (eval 277) line 1
        Selenium::Remote::Driver::__ANON__(${CustomLib}::Driver=HASH(0x4ce3c70), HASH(0x52761a0), HASH(0x4f88018)) called at (eval 279) line 2
        Selenium::Remote::Driver::_execute_command(${CustomLib}::Driver=HASH(0x4ce3c70), HASH(0x52761a0), HASH(0x4f88018)) called at /usr/local/${CustomLib}/Driver.pm line 142
        ${CustomLib}::Driver::_execute_command(${CustomLib}::Driver=HASH(0x4ce3c70), HASH(0x52761a0), HASH(0x4f88018)) called at /usr/local/${CustomLib}/Selenium/Remote/Driver.pm line 1169
        Selenium::Remote::Driver::send_modifier(${CustomLib}::Driver=HASH(0x4ce3c70), "Ctrl", "down") called at /path/to/test_script.test line 110

**Comment by teodesian** [comment]
I think you have to use the WDKeys constant to send ctrl, see the lookup table here:

https://metacpan.org/source/GEMPESAW/Selenium-Remote-Driver-1.20/lib/Selenium/Remote/WDKeys.pm

If that doesn't work it's probably something about how send_keys ups and downs keys, but I suspect that WDKeys usage will fix your problem.

In any case that module needs a heck of a lot better documentation.  That might be what this issue is for.

**Comment by spencebah** [comment]
Sorry.  I should have mentioned that I attempted to use WDKeys, but it didn't appear to have the desired effect.  The two keys appeared to be entered in sequence instead in combination.

    $input_field->send_keys(KEYS->{'control'}, 'v');

However, this approach does work as expected in the Chrome browser (using v56).  I'll go with that for now.  Also, I'll attempt to update to a newer version of Firefox (which may require a newer selenium head) and see if the reported behavior persists.

**Comment by teodesian** [comment]
I'm curious -- what does doing send_modifier(KEYS->{control},'down') and then up do?  I suspect this would work.

**Comment by spencebah** [comment]
The send_modifier call still dies at the first attempt:

    Error while executing command: sendModifier: An unknown server-side error occurred while processing the command.: POST /session/221b29d9-b9f9-4751-890f-d37e84eb8544/modifier
    [...]
    Selenium::Remote::Driver:: send_modifier(${CustomLib}::Driver =HASH(0x61220f8), "\x{e009}", "down") called at /path/to/test_script.test line 147

**Comment by teodesian** [comment]
Appears this is just broken in 2.45 selenium.  Hopefully the new actions method of doing this from #345 fixes this.
