### ISSUE TITLE
Error from send_keys: "sendKeysToElement: Missing 'text' parameter"

### ISSUE THREAD

**Issue by larrymenard** [teodesian/Selenium-Remote-Driver#327]
I've been using both perl and Selenium for ages, but not together.  Just tried Selenium under perl for the first time today.

Error:

> Error while executing command: sendKeysToElement: Missing 'text' parameter at /usr/local/share/perl5/Selenium/Remote/Driver.pm line 327.
>  at /usr/local/share/perl5/Selenium/Remote/Driver.pm line 327.

Test source:

> #!/usr/bin/perl
> use Selenium::Remote::Driver;
> use Selenium::Remote::WebElement;
> 
> use Selenium::Firefox;
> my $firefox = Selenium::Firefox->new;
> $firefox->get('http://www.google.com');
> my $element = $firefox->find_element_by_xpath ('//*[@id="lst-ib"]');
> 
> \# Verify that we got the right WebElement (name should be "q")
> my $name = $element->get_attribute ('name');
> print "\$name = \"$name\"\n";
> 
> \# Error, hangs because it exits before the close()
> $element->send_keys ('search for this');
> 
> sleep (5);
> 
> $firefox->close();
> system ("sudo pkill geckodriver");
> 

Environment:

OS: CentOS 6.9 64-bit
Selenium::Remote::Driver: v2.20
Selenium::Remote::WebElement: v2.20
Perl: v5.10.1
geckodriver: 0.18.0
Firefox: 52.2.0 (64-bit)

**Comment by teodesian** [comment]
It wouldn't shock me -- the coverage for this module is ridiculously low.  I'll try and look at this sometime this week, along with the other bugs associated with the module.

**Comment by teodesian** [comment]
OK, so this works on firefox 54.  The geckodriver page itself claims that you should probably use 54 or better anyways, so that'll probably fix your issue.
