### ISSUE TITLE
Error from get_size(): "getElementSize: GET /session/.../element/.../size did not match a known command"

### ISSUE THREAD

**Issue by larrymenard** [teodesian/Selenium-Remote-Driver#328]
Error text:

> Error while executing command: getElementSize: GET /session/5e4e442c-6bf9-4989-9ffe-e252c0398185/element/3b8d2765-6390-40bb-a2aa-8faf766e9603/size did not match a known command at /usr/local/share/perl5/Selenium/Remote/Driver.pm line 327.
>  at /usr/local/share/perl5/Selenium/Remote/Driver.pm line 327.
> 

(and yes, the "at ..." line is printed twice)

Test source:

> \#!/usr/bin/perl
> use Selenium::Remote::Driver;
> use Selenium::Remote::WebElement;
> 
> use Selenium::Firefox;
> my $firefox = Selenium::Firefox->new;
> $firefox->get('http://www.google.com');
> my $element = $firefox->find_element_by_xpath ('//*[@id="lst-ib"]');
> 
> \# Verify that we got the right WebElement (name should be "q")
> my $name = $element->get_attribute ('name');
> print "\$name = \"$name\"\n";
> 
> \# Error, hangs because it exits before the close()
> my %size = $element->get_size();
> foreach (keys(%size)) {
> 	print "\$size{\$_} \"$size{$_}\"\n";
> }
> 
> sleep (5);
> $firefox->close();
> system ("sudo pkill geckodriver");

Environment:

OS: CentOS 6.9 64-bit
Selenium::Remote::Driver: 1.20
Selenium::Remote::WebElement: v2.20
Perl: v5.10.1
geckodriver: 0.18.0
Firefox: 52.2.0 (64-bit)

**Comment by teodesian** [comment]
Interesting:
Use of uninitialized value in hash element at lib/Selenium/Remote/ErrorHandler.pm line 126.

**Comment by teodesian** [comment]
$resp->{status} is undef returned from the driver.  for why?

**Comment by teodesian** [comment]
Yuck yuck yuck! looks like the error handler has to take into account that the response we get on error is a stack trace, in which we have to pick out an 'error' object rather than just getting a status code like usual.

In any case, it seems the driver thinks this command is unsupported.  Time to hit the books on geckodriver...

**Comment by teodesian** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver/status

Appears that this URI is only partially implemented.  I guess you've hit this bug?  Anyways, this is clearly a response coming from the server and not us.

I'll look at fixing the undefined value warning however; this set of responses from the driver is highly troublesome.  I suppose I should just dump when status is not set.
