### ISSUE TITLE
501 errors when running the testsuite locally

### ISSUE THREAD

**Issue by troglodyne** [teodesian/Selenium-Remote-Driver#333]
Spotted while running 'dzil test' when making PR 332:

    t/Test-Selenium-Remote-Driver-google.t .. 1/? Error while executing command: Server returned error code 501 and no data at /home/user/git/Selenium-Remote-Driver/.build/fEM9xZANev/blib/lib/Selenium/Remote/Driver.pm line 327.
    at /home/user/git/Selenium-Remote-Driver/.build/fEM9xZANev/blib/lib/Selenium/Remote/Driver.pm line 327.
    at /home/user/git/Selenium-Remote-Driver/.build/fEM9xZANev/blib/lib/Test/Selenium/Remote/Role/DoesTesting.pm line 48.

Several tests fail for this reason. I've ran into similar failures privately before when updating LWP mocks in S::R::D submodule testing.

**Comment by troglodyne** [comment]
Seems to fail over on Travis too:
https://travis-ci.org/teodesian/Selenium-Remote-Driver/jobs/262927260

**Comment by teodesian** [comment]
Doesn't fail on master.  Sure it's not an issue with your commit?

https://travis-ci.org/teodesian/Selenium-Remote-Driver/builds/260007742

**Comment by troglodyne** [comment]
K, will close it, I'm guessing I'll need to figure out a way to regen those mocks or just apply more comprehensive mocking where that is failing
