### ISSUE TITLE
Test::Selenium::Chrome ->find_element_ok ERROR

### ISSUE THREAD

**Issue by davewood** [teodesian/Selenium-Remote-Driver#334]
I changed this line in my test from
`$driver->find_no_element_ok( "testcontact-sqybpkqx", "link_text" );`
to
`$driver->find_element_ok( "testcontact-sqybpkqx", "link_text" );`
and now my code is broken
I guess it's supposed to say [not ok] in the TAP output but instead I get this:
```
(...)
ok 15 - clear
ok 16 - send testcontact-sqybpkqx



[ERROR]
Test::Selenium::Chrome=HASH(0x27a2670)coercion for "id" failed: When passing in an object to the WebElement id attribute, it must have at least one of the ELEMENT or element-6066-11e4-a52e-4f735466cecf keys. at /home/epplication/perl5/perlbrew/perls/perl-5.22.2/lib/site_perl/5.22.2/Selenium/Remote/Driver.pm line 968.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 16.
```

**Comment by teodesian** [comment]
Looks like a bug -- the usual "klingon programming" you see from perlers (better to die than return() in failure...).  Needs moar eval {} -- this died when it couldn't do some extra processing on an element because it didn't exist in the first place.

I'll look at fixing this in the next release.
