### ISSUE TITLE
S::R::D not handling errors correctly

### ISSUE THREAD

**Issue by yewtc** [teodesian/Selenium-Remote-Driver#343]
perl 5.24.3
SRD 1.20
Chrome 62.0.3202.94

So being a dummy I did a call like $srd->find_elements("//table[@class='class']"). It failed because quotes were the wrong way wrong and it was looking for //table[='class']. The problems is that this causes ...

Not an ARRAY reference at /usr/local/share/perl5/Selenium/Remote/Driver.pm line 999

The reason is that the call to driver "succeeds" in  returning an error message, in particular it doesn't throw and error from _execute_command and hence doesn't go down the if ($@) branch, this means later on it is assuming $ret_data is an array ref.

**Comment by teodesian** [comment]
Silly perlers using a dynamic language and thinking they don't need guard clauses.  Wheee

Will look into this tonight.

**Comment by teodesian** [comment]
I've beefed up the error handling in general as part of #345.  This now reports like so:

`Error while executing command: invalid selector: Given xpath expression "//table[='class']" is invalid: SyntaxError: The expression is not a legal expression. at /home/doge/Code/Selenium-Remote-Driver/lib/Selenium/Remote/Driver.pm line 792.
 at /home/doge/Code/Selenium-Remote-Driver/lib/Selenium/Remote/Driver.pm line 758.`

That sounds like it should be sufficient for your purposes.
