### ISSUE TITLE
switch_to_frame

### ISSUE THREAD

**Issue by hornschorsch** [teodesian/Selenium-Remote-Driver#344]
`$driver->switch_to_frame($frameid);  # $frameid is a string`

returns the following error:

> Error while executing command: switchToFrame: A request to switch to a frame could not be satisfied because the frame could not be found.: frame id has unexpected type
> Build info: version: '3.7.1', revision: '8a0099a', time: '2017-11-06T21:07:36.161Z'
> System info: host: 'mozart', ip: '192.168.100.5', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.17', java.version: '1.8.0_111'
> Driver info: driver.version: unknown at /usr/local/share/perl5/Selenium/Remote/Driver.pm line 327.
>  at /usr/local/share/perl5/Selenium/Remote/Driver.pm line 327.

The selenium-server log says:

> 14:18:24.306 INFO - Handler thread for session 058b6032-b25f-43fc-989c-34cb1640b72f (firefox): Executing POST on /session/058b6032-b25f-43fc-989c-34cb1640b72f/frame (handler: ServicedSession)
> 14:18:24.310 INFO - HTTP Status: '400' -> incorrect JSON status mapping for 'no such frame' (404 expected)

S:R:S is Version 1.20, selenium-server 3.7.1, geckodriver tested with 0.14 and 0.18.

**Comment by teodesian** [comment]
So it's just returning an error string 'no such frame' rather than 404 as suggested by spec.  And we've gotta write some special handler to deal with it, I assume.

**Comment by hornschorsch** [comment]
But the frame is there, the same script worked with SRD 1.01 and selenium 3.0.1.

Now i downgraded selenium server step by step and with 3.4.0 it works again. All newer versions fail.

Here is additionsl debug output, 3.4.0:

`REQ: POST, http://localhost:4444/wd/hub/session/5d42ef2e-9767-481c-94b0-42a205e9c763/frame, {"id":"iframeContainer"}
RES: {"state":"success","sessionId":"5d42ef2e-9767-481c-94b0-42a205e9c763","hCode":1866838345,"value":null,"class":"org.openqa.selenium.remote.Response","status":0}`

and 3.7.1:

```
REQ: POST, http://localhost:4444/wd/hub/session/bb2914eb-4ec2-447e-9e80-395088f9e1f6/frame, {"id":"iframeContainer"}
RES: {"state":"no such frame","sessionId":null,"hCode":1251219295,"value":{"additionalInformation":"\nDriver info: driver.version: unknown","localizedMessage":"frame id has unexpected type\nBuild info: version: \u00273.7.1\u0027, revision: \u00278a0099a\u0027, time: \u00272017-11-06T21:07:36.161Z\u0027\nSystem info: host: \u0027mozart\u0027, ip: \u0027192.168.100.5\u0027, os.name: \u0027Linux\u0027, os.arch: \u0027amd64\u0027, os.version: \u00273.10.17\u0027, java.version: \u00271.8.0_111\u0027\nDriver info: driver.version: unknown","systemInformation":"System info: host: \u0027mozart\u0027, ip: \u0027192.168.100.5\u0027, os.name: \u0027Linux\u0027, os.arch: \u0027amd64\u0027, os.version: \u00273.10.17\u0027, java.version: \u00271.8.0_111\u0027","supportUrl":null,"cause":null,"stackTrace":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],"suppressed":[],"message":"frame id has unexpected type\nBuild info: version: \u00273.7.1\u0027, revision: \u00278a0099a\u0027, time: \u00272017-11-06T21:07:36.161Z\u0027\nSystem info: host: \u0027mozart\u0027, ip: \u0027192.168.100.5\u0027, os.name: \u0027Linux\u0027, os.arch: \u0027amd64\u0027, os.version: \u00273.10.17\u0027, java.version: \u00271.8.0_111\u0027\nDriver info: driver.version: unknown","hCode":298817455,"class":"org.openqa.selenium.NoSuchFrameException","buildInformation":null},"class":"org.openqa.selenium.remote.Response","status":8}
```

**Comment by hornschorsch** [comment]
According to https://w3c.github.io/webdriver/webdriver-spec.html#dfn-switch-to-frame the argument to switch_to_frame must be a number or a web element.

$driver->switch_to_frame($driver->find_element_by_id($frameid));

does the job...

**Comment by teodesian** [comment]
So not only did they change the output, they also changed the expected inputs.  wheeeee.  OK, will look at this on the weekend.

**Comment by teodesian** [comment]
This issue appears to be a subset of #345.  Further investigation will be on hold until I can fully implement the WD3 spec.

**Comment by teodesian** [comment]
closing this out, it doesn't seem to be a problem anymore.
