### ISSUE TITLE
W3C protocol support

### ISSUE THREAD

**Issue by LuriaA** [teodesian/Selenium-Remote-Driver#345]
Hi. The Firefox and IE drivers for Selenium now use the W3C Wire Protocol rather than the original JSON Wire Protocol. The two are very similar, but the 'Actions' APIs are very different. Are there any plans to support the new protocol?

**Comment by teodesian** [comment]
I assume we'll have to do that at some point.  I'll have to do some research before I can give a reasonable work estimate -- I'll try and do that this weekend.

**Comment by teodesian** [comment]
ok, so it looks like the first thing I should do is figure out a reliable method to discern whether the driver supports WD3 versus WD2.  I guess I could just try to do something WD2 can't do, but I would prefer to be able to get it out of something like a version call.

Next, I'll need to re-factor Selenium::Remote::Command into two modules, one for each type.  I would also make it simply parse a document of API specs (a copy/paste from the spec listing) for ease of use and update in the future.

Finally, _execute_command would need to consult the API version and route the request through the correct Remote::Command module.

I may also have to have special handlers created for both to mangle input into the way that their version wants it so that I don't break callers of S::R::D on the new version of selenium.  Furthermore, I'll need custom error handling code for each path.

Effectively I'll be bifurcating a large amount of the module.  This will be a large re-factor; I'll have to get my employer on-board to have any hope of getting this done in a timely fashion.  I should also wrap-up any outstanding branches/issues I want to merge before doing a major version bump like this.

**Comment by teodesian** [comment]
The bad news:

v2 isElementDisplayed NOT present in v3 spec!!!
v2 screenshot NOT present in v3 spec!!!
v2 availableEngines NOT present in v3 spec!!!
v2 setOrientation NOT present in v3 spec!!!
v2 getOrientation NOT present in v3 spec!!!
v2 executeScriptGecko NOT present in v3 spec!!!
v2 clickElement NOT present in v3 spec!!!
v2 getWindowPosition NOT present in v3 spec!!!
v2 getCapabilities NOT present in v3 spec!!!
v2 getLogTypes NOT present in v3 spec!!!
v2 sendModifier NOT present in v3 spec!!!
v2 getLog NOT present in v3 spec!!!
v2 deleteLocalStorageItem NOT present in v3 spec!!!
v2 buttonUp NOT present in v3 spec!!!
v2 doubleClick NOT present in v3 spec!!!
v2 uploadFile NOT present in v3 spec!!!
v2 getElementLocation NOT present in v3 spec!!!
v2 elementEquals NOT present in v3 spec!!!
v2 cacheStatus NOT present in v3 spec!!!
v2 findChildElements NOT present in v3 spec!!!
v2 getContext NOT present in v3 spec!!!
v2 mouseMoveToLocation NOT present in v3 spec!!!
v2 getGeolocation NOT present in v3 spec!!!
v2 executeAsyncScriptGecko NOT present in v3 spec!!!
v2 setImplicitWaitTimeout NOT present in v3 spec!!!
v2 describeElement NOT present in v3 spec!!!
v2 setElementSelected NOT present in v3 spec!!!
v2 getLocalStorageItem NOT present in v3 spec!!!
v2 submitElement NOT present in v3 spec!!!
v2 getElementLocationInView NOT present in v3 spec!!!
v2 setWindowPosition NOT present in v3 spec!!!
v2 setAsyncScriptTimeout NOT present in v3 spec!!!
v2 buttonDown NOT present in v3 spec!!!
v2 toggleElement NOT present in v3 spec!!!
v2 getSessions NOT present in v3 spec!!!
v2 setContext NOT present in v3 spec!!!
v2 sendKeysToActiveElement NOT present in v3 spec!!!
v2 setGeolocation NOT present in v3 spec!!!

The good news:

v3 getElementProperty NOT present in v2 spec!!!
v3 minimizeWindow NOT present in v2 spec!!!
v3 fullscreenWindow NOT present in v2 spec!!!
v3 elementScreenshot NOT present in v2 spec!!!
v3 screenshotTake NOT present in v2 spec!!!
v3 switchToParentFrame NOT present in v2 spec!!!
v3 getTimeouts NOT present in v2 spec!!!
v3 releaseGeneralAction NOT present in v2 spec!!!
v3 getNamedCookie NOT present in v2 spec!!!

So, as I thought I'll have to have 2-way tries/fallback with some methods not implemented in both.  yay

**Comment by teodesian** [comment]
I think the timeouts are just more advanced usage of the setTimeout function -- I'll have to look deeper into the calling convention there

**Comment by teodesian** [comment]
also looks like no_content_success may always be 0.  that could be nice; seems they've also standardized what some error codes "mean" in these contexts

**Comment by teodesian** [comment]
Interesting -- so they also intend protocol extensions to just 'extend' the list of commands -- I might be able to consider some of these more funky 'workaround' commands as vendor protocol extensions and load them as 'extra' v3 spec modules.

**Comment by teodesian** [comment]
So it seems create session also returns the capabilities now.  I guess I can use that as a way of figuring out whether we support v3 at all, since there's no way to actually query the version directly.

**Comment by teodesian** [comment]
ok, I think I'm about 80% done.  Now for the other 80% -- testing, possible data formatting issues, adding new methods for the extra v3 methods and hunting down the vendor methods and implementing those dang things.

**Comment by teodesian** [comment]
15:28:15.334 INFO - Capabilities {acceptSslCerts: true, browserName: firefox, javascriptEnabled: true, version: } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
Starting ChromeDriver 2.34.522913 (36222509aa6e819815938cbf2709b4849735537c) on port 3121
Only local connections are allowed.
15:28:16.251 INFO - Detected dialect: OSS
15:28:16.558 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@26b28469
15:28:16.559 INFO - Handler thread for session dd2848c53c6e989d07adcc3ba2ba437f (chrome): Executing POST on /session/dd2848c53c6e989d07adcc3ba2ba437f/url (handler: ServicedSession)

wait, what?  I told the thing to use firefox, and it uses chrome.  Clearly some differences in the way we have to pass data to sel3.  Joy

**Comment by teodesian** [comment]
so it looks like we can do two things in capabilities
`alwaysMatch and firstMatch`

The idea here is to do alwaysMatch to give the user exactly what they want, while firstMatch can be used to try any 'available' capabilities on the server matching your list of caps objects passed.

Given the module has basically operated in a mustMatch sort of way, I'll implement that, and have the firstMatch caps be sort of a feature request thing.

**Comment by teodesian** [comment]
aw, jeez, that means that my strategy of looking for the metadata returned will be too late, since I have to structure the data call differently just to make a session!  I guess I gotta burn a session because there's no service catalog or version endpoint.  I guess I'll investigate whether /status is useless  too real quick...

**Comment by teodesian** [comment]
/status is totally useless, and they clearly aren't following the spec, as neither the "ready" or "message" attrs are present on either chrome or firefox.  YAY!

 `$VAR1 = {`
`          'cmd_return' => 1,`
`          'sessionId' => '259a89a92ddfcbd915d38eb7783f6da5',`
`          'cmd_status' => 'OK'`
`        };`

**Comment by teodesian** [comment]
wait!  I'll just make it a mutant child where we have the new keys, and the old keys uselessly hanging around in the hash too!  WHEEE

**Comment by teodesian** [comment]
getting somewhere now:
`Could not create new session: Illegal key values seen in w3c capabilities: [acceptSslCerts, javascriptEnabled, platform, version] at at/sanity.test line 8.`

So, it falls back to v2 if you just specify the caps the 'old way'.  we'll see how well they go along with things soon.

**Comment by teodesian** [comment]
OK, so I'm gonna have to map our caps names to the new caps names too.  Yay

**Comment by teodesian** [comment]
aaaand it defaults to v2 if we pass v2 options.  Guess I'll have to make a $FORCE_WD3_SESSION thingy

**Comment by teodesian** [comment]
filed https://github.com/SeleniumHQ/selenium/issues/5315

**Comment by teodesian** [comment]
yee haw, have loaded a web page

**Comment by teodesian** [comment]
Looks like we can fall back and execute selenium 2 commands even if we start a session via selenium3 conventions!  This should make 100% compatibility possible.

**Comment by teodesian** [comment]
The whole actions stuff makes the blood pressure rise:

`17.5.1 Payload Format`
`This section is non-normative.`

uhhhh, thanks guys.  I guess we just have to guess based on the processing spec; what I've gathered is along the following lines:

`{ actions => {`
`    type => 'key|pointer|none|something_else',`
`    id => "Some ID we get from listing the input sources somehow",`
`    action => {`
`        id => "AUTO_INCREMENT, I assume?",`
`        key => "whatever key to type in IFF key type action", #XXX it actually probably wants value`
`        subtype => "keyUp|KeyDown if key, pointerUp|pointerDown|pointerMove|pointerCancel if pointer, ``pause if any type",
`        duration => "number of ticks to pause if none/key subtype; no. ticks to take moving the pointer if `a `pointer event",
`        button   => "natural number corresponding to what button on the joypad err 'pointer' when doing ``pointerUp/Down.  How the hell do I get these numbers? unknown",
`        origin   => "Point-Of-Origin for the pointer when doing pointerMove, allowed values are `'viewpoint' `and 'pointer' (relative and absolute from 0,0)",
`        x        => "x px offset from POO to move to",`
`        y        => "y px offset from POO to move to",`
`        #come on guys, you really are getting lazy here, give us a Z-axis for my oculus`
`    }` 
`}};`

**Comment by gerhardj** [comment]
that's how I felt, when I implemented some stuff with this actions API :)

**Comment by teodesian** [comment]
Yeah, I think I can get calling of everything hooked up before the end of the week.

It'll probably take next week to normalize output data between the two versions (if we don't, people's tests break...)

Thanks for the commit link @gerhardj, that should speed things up a bit; well, that and cribbing from the python/ruby drivers.

**Comment by teodesian** [comment]
Hmm, the new actions API concerns me, as it seems to be a breaking change as far as I can see so far.  We can't for example keep a modifier key jammed down globally; it'll only be depressed in the context of an action chain.  Maybe that's what releaseGeneralAction is for? not sure.

Anyways, I've got everything in S::R::D done with the exception of the action methods and the new one, switchToParentFrame.  After that, it's on to verifying everything in WebElement works and adding getElementProperty.

**Comment by teodesian** [comment]
so, I've re-implemented move_to and click in action chains.  The problem is that despite me doing what appears to be the same exact thing as the python bindings, and the API seeming happy with the input, nothing seems to happen if I say, move to an element and then call click().  I am concerned that if I don't do everything in the same chain it's just moving the mouse back to it's default position; though I have no way of knowing if this is the case, as the actions API has *no way* to read current device state.

**Comment by teodesian** [comment]
Yep, that's what is going on; it's implicitly clearing mouse position data after each chain is performed.  This is a *significant* defect in the API that will require a great deal of code complexity to deal with.

Effectively, I'm going to have to *not* perform any mouse moves until something like a click() is called; and there are probably some situations where a user performs some other action where I should discard the prior chain (e.g. elementClick).

**Comment by teodesian** [comment]
Seeing another horrid bug.  When you type into a text field, you would expect:
`$field->get_attribute('value')`
to return the same thing as
`document.querySelector('[name="text"]').value`
Alas, not so.  It just returns whatever it was at page load.  Basically useless.

**Comment by teodesian** [comment]
I think I may have figured out what is going on.  Basically they're no longer playing fast and loose with the definition of 'attribute' -- e.g. the attribute is whatever the value in the tag says it is, rather than the current value.  the 'property' is what we'd want to preserve previous behavior.

That's gonna break a lot of people's tests if I don't have something like a 'no_I_really_mean_it' flag on get_attributes(), to have it actually get attrs rather than properties.

**Comment by teodesian** [comment]
So, drag() is currently disabled.  I think I'm gonna leave it like that for the purpose of this issue, and just file an issue to implement drag & drop w/ fallback to the JSONWire old method restored for those using old selenium + browser stacks.

**Comment by teodesian** [comment]
dangit, I gotta do all those silly 'server-less' implementations too and make sure they work.  more work for me

**Comment by teodesian** [comment]
Hmm, seems I'm gonna have to do some more work to get the firefox_profile feature in the constructor working.  Also need to do per-browser translation of extra_capabilities into the browser specific option name.

**Comment by teodesian** [comment]
Ok, so of course chrome doesn't work for mysterious reasons.  Yay.
Add that up to the direct firefox usage.

After I fix those (and I guess test on edge now too), I think I'll *finally* be done.

**Comment by teodesian** [comment]
so, chrome doesn't follow the spec, and return capabilities as a parameter in the return.  Naughty naughty.  This means I'll have to make another shim for it.

**Comment by teodesian** [comment]
OK, I'm gonna leave Selenium::Firefox dead as is, and move on to checking edgeDriver.

**Comment by teodesian** [comment]
Finally done! hooray

**Comment by LuriaA** [comment]
You are awesome! When it will be available on cpan? And what about the Internet Explorer?

**Comment by teodesian** [comment]
I'll be making a release to CPAN before the end of the week, supposing I don't find any major issues running my employer's testsuite with it (even more real-world testing).

I got the MicrosoftEdge browser/driver working.  Do you need me to check/work on a specific version of IE?  If so it might take a while longer to get the test environment set up.

**Comment by LuriaA** [comment]
As customer still uses IE instead of Edge we need the IE testing. At least IE 11 on Windows 7 and 10 (because most of the problems were catched on them).
And also will the IE be able to work without the selenium-standalone-server?

**Comment by teodesian** [comment]
I haven't done testing on any of the direct drivers save firefox, and it's broken (but it was before too).  For now, doing 
`java -Dwebdriver.internetexplorer.driver=... -jar selenium-server.jar`
should do the trick, as it always has.

I'll look into IE11 on windows ten tonight.

**Comment by teodesian** [comment]
I got IE11 working last night in #360.

**Comment by gerhardj** [comment]
Just wanted to report back, that I tried our testsuite with 1.23 from CPAN, and everything passed after a few minor adaptions. Thanks a lot!
