### ISSUE TITLE
API inconveniences: find_child_element() never returns undef

### ISSUE THREAD

**Issue by vdudouyt** [teodesian/Selenium-Remote-Driver#347]
I'm attempting to use Selenium::Remote::Driver in a pretty big functional testing project. Unfortunately, I can't use find_child_element() at all because displaying a custom error message each time when an element wasn't found in place is an essential point for me.

Instead of that, each time I'm forced to write my code in the following way:

```perl
my ($child1) = $driver->find_child_elements($parent1, 'xpath expression 1');
diag("Problem explanation 1") if !$child1;

my ($child2) = $driver->find_child_elements($parent2, 'xpath expression 2');
diag("Problem explanation 2") if !$child2;

...
```

While I would really love to write as follows:

```perl
my $child1 = $driver->find_child_element($parent1, 'xpath expression 1') || diag("Problem explanation 1");
my $child2 = $driver->find_child_element($parent2, 'xpath expression 2') || diag("Problem explanation 1");
...
```

Can we return undef if an element wasn't found by any chance? Even if somebody will try to access it as an object by a mistake, an error message that he will receive from Perl interpreter will not be much more cryptic that we have at this moment.

Thanks for your attention!

**Comment by teodesian** [comment]
Every other find_* method throws an exception if it can't find what it's looking for; I think that's the current behavior of find_child_element.  if it isn't that probably should be fixed to throw rather than return undef.

As to your golfing needs, putting things into asserts would be the rightful remedy:


`use Test::Fatal;`
`is( exception { $child = $driver->find_child_element(...) }, undef, "Couldn't do thingy") or diag("extra info");`

**Comment by vdudouyt** [comment]
I doubt that I can include 'Test::Fatal' in the same module because I have to strictly follow the PageObject pattern. But anyway, thanks for your suggestion!

**Comment by teodesian** [comment]
In that case you could probably do
` eval {$child = $driver->find_child_element(...) } or diag(...);`

Probably a few other ways around it too.

**Comment by teodesian** [comment]
Too much relies on this returning a blank array ref.  Going to close wont fix.
