### ISSUE TITLE
Non-xpath locators don't look to be working in find_child_elements()

### ISSUE THREAD

**Issue by vdudouyt** [teodesian/Selenium-Remote-Driver#348]
When I'm trying to locate an existing element by using a name locator, it always fails with an error message (which means that an element wasn't found, accordingly to my experience):

```perl
my ($element) = $driver->find_child_elements($pm->{element}, 'name=my_text_input');
# => Runtime error: coercion for "id" failed: When passing in an object to the WebElement id attribute, it must have at least one of the ELEMENT or ...
```

But when I use it's XPath equivalent, everything works like a charm:

```perl
my ($element) = $driver->find_child_elements($pm->{element}, './/input[@name="my_text_input"]');
# => Selenium::Remote::WebElement=HASH(0x769acd0)
```

I know about find_element_by_* family of methods which looks to be working, but it is not capable of searching child elements, AFAIR.

Do we have an issue in Selenium bindings, or I'm just doing something wrong?

**Comment by teodesian** [comment]
You are failing to pass the locator type as the third argument.  As such it is still parsing it as xpath and failing.  Try something like this:

`my ($element) = $driver->find_child_elements($pm->{element}, 'input[name="my_text_input"]','css');`

**Comment by teodesian** [comment]
Closing issue, assuming this was a usage issue.
