### ISSUE TITLE
API inconveniences: I can't use method chaining with clear() / send_keys()

### ISSUE THREAD

**Issue by vdudouyt** [teodesian/Selenium-Remote-Driver#349]
In the most of cases, I'm calling clear() before using send_keys(). It would be really great if I could use method chaining to write it in the following way:

```perl
$driver->clear()->send_keys($some_value) if $some_condition;
```
instead of writing it like that each time:
```perl
if($some_condition)
{
   $driver->clear();
   $driver->send_keys();
}
```

Can we make send_keys() returning $self for that?

P.S. Here is probably the last issue that I submit in this GitHub repository for a while. Actually, #347, #348 and #349 are the only problems frustrating me for years of using Selenium::Remote::Driver. Perhaps I just need to write a simple wrapper instead of pestering you :)

**Comment by teodesian** [comment]
For our own testing purposes we subclassed S::R::D at our firm years ago.  Sometimes it's the right move.  That said, I don't see anything bad right off allowing these methods to chain -- I'll have to check and see what if anything this might break (aside from unit tests).

**Comment by teodesian** [comment]
Looks to me like this would break the assumptions in Test::Selenium::Remote::Driver, so unfortunately no.  I think I'm gonna wontfix this one.
