### ISSUE TITLE
Headless Mode for Firefox

### ISSUE THREAD

**Issue by rabbiveesh** [teodesian/Selenium-Remote-Driver#351]
I can't seem to figure out how to use this to start firefox in headless mode. Perhaps it should  be enabled by default, or at least documented somewhere.

Excuse my ignorance if I just missed it in the docs.

**Comment by gempesaw** [comment]
Are you using the main module Selenium::Remote::Driver with the standalone server jar running somewhere? or the binary startup Selenium::Firefox?

**Comment by rabbiveesh** [comment]
Oh, I apologize for not specifying. I'm using Selenium::Firefox.

**Comment by teodesian** [comment]
what does
`perl -MSelenium::Firefox::Binary -e 'print Selenium::Firefox::Binary::firefox_path()."\n";'`
say?

**Comment by rabbiveesh** [comment]
Your command shows '/usr/bin/firefox', which is as expected.

I've tried invoking the builder in the following ways:
```
my $driver = Selenium::Firefox->new();
my $driver = Selenium::Firefox->new(custom_args => '--headless');
my $driver = Selenium::Firefox->new(firefox_binary => '/usr/bin/firefox --headless');
my $driver = Selenium::Firefox->new(firefox_binary => "'/usr/bin/firefox --headless'");

```
None of these starts firefox in headless mode. They all start a normal firefox instance (which is really slow).

I'm working on Ubuntu Xenial (16.04), with FF 57.0.4. It's definitely not a problem with geckodriver, b/c the selenium python bindings work fine with headless mode.

**Comment by gempesaw** [comment]
https://github.com/mozilla/geckodriver/issues/1089#issuecomment-349612254

```
use Selenium::Firefox;

$ENV{MOZ_HEADLESS} = 1;
$driver = Selenium::Firefox->new();
$driver->get('https://www.google.com');
print $driver->get_page_source;
$driver->shutdown_binary;
```

Setting the MOZ_HEADLESS environment variable works for me: SRD v1.20, geckodriver v0.19.1, FF v57.0.4. 

Unfortunately, the `custom_args` constructor argument applies to the webdriver binary (in this case, geckodriver). Double unfortunately, the `firefox_binary` constructor argument is passed to geckodriver as "what file should we execute to start firefox" kind of thing, and not "what's the string we should use to start firefox". I'm actually kind of surprised those last two started a firefox at all...

`geckodriver` didn't seem to have any options for passing command line arguments to the browser that it eventually starts. If you don't like this env var solution, another other option would be to figure out how to pass it in the `desiredCapabilities` during start up, but I couldn't find any examples of that yet.

**Comment by teodesian** [comment]
I'd be fine with making a shim that just sets the $ENV var for the session -- it's not like we don't have a bunch of other 'synthetic' capabilities (shims) already in there.

**Comment by hornschorsch** [comment]
When using the selenium server you can do this with:

```
$driver = Selenium::Remote::Driver->new(
    'extra_capabilities' => {
        'moz:firefoxOptions' => {
            "args" => [ "--headless" ],
        },
    }
);

```

**Comment by teodesian** [comment]
That would work too -- especially now that I'm correctly injecting that stuff with the WD3 code from #345.  I'll think of adding that in as a constructor option in 1.22.

**Comment by teodesian** [comment]
I got this working in the new code.

Unfortunately there's a bug in geckodriver such that it prefers old capabilities (and we pass them for compatibilities sake), and as such args are ignored unless we do:

$Selenium::Remote::Driver::FORCE_WD3 = 1 before calling new().

However, after that, just pass args => ['-headless'] as part of extra_capabilities and all should be well.

**Comment by ylavoie** [comment]
```
use Selenium::Firefox;

$ENV{MOZ_HEADLESS} = 1;
$driver = Selenium::Firefox->new();
$driver->get('https://www.google.com');
print $driver->get_page_source;
$driver->shutdown_binary;
```
works flawlesly for me too with SRD v1.20, geckodriver v0.19.1, FF v57.0.4.
Keeping geckodriver and FF constant, it fails for any SRD version from 1.21 to 1.25 with `Could not create new session: Unable to find a matching set of capabilities`

What did I miss?
