### ISSUE TITLE
Get attribute problem on IE11

### ISSUE THREAD

**Issue by LuriaA** [teodesian/Selenium-Remote-Driver#362]
I've just updated the selenium standalone server, IEdriverServer and S::R::D to the last versions and got my tests broken on IE11 under Windows 7:
D 2018-01-22 11:37:37:459 command.cc(36) Raw JSON command: { "name" : "getElementProperty", "locator" : { "sessionid" : "fd91b97a-b668-43bc-86bc-9fb2f71c7cb9", "id" : "abdf25d2-624f-40ad-8fcf-9b12184f28ec", "name" : "enabled" }, "parameters" : {} }
D 2018-01-22 11:37:37:459 IECommandExecutor.cpp(546) No alert handle is found
I 2018-01-22 11:37:37:459 Browser.cpp(130) No child frame focus. Focus is on top-level frame
W 2018-01-22 11:37:37:475 Element.cpp(291) -2147352570 [Unknown name.]: Unable to get dispatch ID (dispid) for property enabled
D 2018-01-22 11:37:37:490 server.cc(338) Response: {"value":null}

And I get this error on any element property/attribute.
Is it a problem with S::R::D or with the Selenium itself?

**Comment by teodesian** [comment]
Not sure right now -- I tested this on IE11, and get_attribute was working.

What value were you expecting to be returned by the server?  I assume you were trying to call is_enabled()?

If so, I've found a bug along those lines as well -- the driver now will return 0 if the 'enabled' property is not present in an element.  Previously if the element was not an input, it would just return true.  Would this basically be what you are encountering?

**Comment by teodesian** [comment]
Furthermore, I was checking the wrong prop() in my polyfill -- enabled instead of 'disabled'.  whee

**Comment by LuriaA** [comment]
Yes, I'm using is_enabled. But I'm not sure that this is the problem because the get_attribute produces the same error :( Say, I tried to get attribute 'class' and get the error. Maybe it also returns 0 if attribute is not present in element?

**Comment by teodesian** [comment]
Possibly.  I'll have to look into what get_attribute('class') on an element with and without it does.

To clarify, are you getting an exception thrown, or just false being returned?

**Comment by teodesian** [comment]
Unrelated to the other attribute issues you may be seeing:

Give the above patch a shot -- see if it corrects the issue with is_enabled().

**Comment by LuriaA** [comment]
The "Response: {"value":null}" is returned and it is used as false.
Unfortunately, I can't try fix for now, only tomorrow.

**Comment by teodesian** [comment]
No problem -- I'm gonna try it out on my own tests (which are failing on firefox for similar reasons).

**Comment by teodesian** [comment]
I think fixing is_enabled is what we need done here?  Anyways, file another issue with steps to reproduce if you're having issues with other get_attribute/get_property calls.
