### ISSUE TITLE
Failed to create selenium remote driver at Wed Feb 14 00:00:00 2018 - Could not create new session: Illegal key values seen in w3c capabilities: [chromeOptions]

### ISSUE THREAD

**Issue by mjegh** [teodesian/Selenium-Remote-Driver#368]
I upgraded from 1.20 to 1.24 for what looked like bug fixes and now I get this error.

**Comment by teodesian** [comment]
It's a bug in chromedriver.  See the section in the POD here:

https://metacpan.org/pod/Selenium::Remote::Driver#Chrome-Notes

Long story short, do this:

`$Selenium::Remote::Driver::FORCE_WD2=1;` and you should be fixed-up.

**Comment by teodesian** [comment]
Upon closer reading, I think what they mean by "use the DesiredCapabilities class" is "we don't support spawning new sessions via the WC3 method".  I'll just set FORCE_WD2=1 and break it off for chrome.

**Comment by teodesian** [comment]
Seems to work.  Good enough

**Comment by mjegh** [comment]
Sorry, I forgot to say I made the change you suggested and it worked fine. Thanks for the suggestion.
