### ISSUE TITLE
Headless mode for Firefox on 1.21+

### ISSUE THREAD

**Issue by ylavoie** [teodesian/Selenium-Remote-Driver#371]
This follows #351
```
use Selenium::Firefox;

$ENV{MOZ_HEADLESS} = 1;
$driver = Selenium::Firefox->new();
$driver->get('https://www.google.com');
print $driver->get_page_source;
$driver->shutdown_binary;
```
works flawlesly for me too with SRD v1.20, geckodriver v0.19.1, FF v57.0.4.
Keeping geckodriver and FF constant, it fails for any SRD version from 1.21 to 1.25 with Could not create new session: Unable to find a matching set of capabilities

What did I miss?

**Comment by teodesian** [comment]
You missed a big re-factor to try and get WC3 methods working.  That has more or less worked.

I haven't spent much time on the standalone drivers, due to not having time to figure them out yet.

I have had success doing a traditional selenium setup using

`Selenium::Remote::Driver->new( ..., extra_capabilities => { args => ['-headless']);`

That said, now that I have an idea of how to use this thing (It's *always* failed for me regardless of the version), I will look at what's wrong with it.

**Comment by teodesian** [comment]
Have reproduced, looking into it

**Comment by teodesian** [comment]
request:
`{
          'capabilities' => {
                              'alwaysMatch' => {
                                                 'platformName' => 'ANY',
                                                 'moz:firefoxOptions' => {
                                                                           'profile' => 'UEsDBBQAAAAIAPV6VUx/xBZIrwMAAOkMAAAHAAAAdXNlci5qc51XTW8bOQy991cUPm2BRnCSFmh3T9k0CyxQbIoaQY+CRuJ4FGskrURl7H9faj4axx7POL1lZFIkH8n3lBQhcB+g/GPRQKGCfqJvEWOqgSeLIUUExTUdQFi8f0sH8O6vN+nZSwkUAbwLqO2aeWe03LF8uEpFTX7a2TsrCgOK3Eth4oG/BWxc2LBaWLGGC1eWRlu4iCgwxXGXIriGvlgEU8bkc2yWgiHjxeKEpSih/TvnWAvTUMoMptJSribDLZdVcARFlEF75CFZjroG8rlenkqqrTmioxABWiBLuoPLIGI1XZDS0RuxA3V3uVz951DLHOnDuDGKIjIqxN7bW+MijF8NWwTbJsQK4+TG6IgzlcMTOmcigxBckOTpzD5YxyNQi0ABABGYglIkg9/oPLLcGHK4+nT1abaEew92PB9P4HmM2ZjXTgkznX7OfaORIRioAcOOdRe09lfjedDEbZijDLiFptFWuebYOOq1dZZaWkNdQFi1nzMTShdZ44Tqp5umo3LNjwrsipYmL8yce826dJhKtZ9swlB3v09DQBqp7DPqMoShogncYYVE4RL+WRhhN4tXr/q39vBGSugRP6tDkw19FE+iW7/J+vcGPXlKama/9251Hlu33Jt/7W038KMxhPdnXT4Ae/fw9YZdM/EMx/GdW6+JLIQxrKk0QZL3M8D/SYcpaurawMmNP0YO2xxAd+M4R9EVCINV901sFZ6IZVipQ8Tv6cQKHmNriZzK3UNsRWEOAUeaErQax/RZdSgHKN2W97Txefn5+mADQaagcUfZGqC/WMSgJXIX9Fpb3g3keD572tY2Y0/bJAQcx22QpgrRM1/pWO0u8s+e9PHCgF1j5vOrjx/Haw8gVN5AQJAU6J8M8Q31QM6sYwQRZNUjPV7OoJI0kJHRELiGFzvek+9rZyD5TFGTIv2SKTwxy3kLYKiCQKJ5nvULlT7PI9No8qwijc5Z8WHUWE0CbDN6i8zTARYnJ9q49fplwNOtoSN1b3+0lBwvl0zTFLmH71+neXPw7rs2U1IFxAWyArn50vXz7+6X02TQczxvFUzRYtg1zy0d9zjaosP1Ody6Q4wbMDK/iWb14lckGQftmhmXXzqc+xOsMMcyvMfBIqGbJaxs9KUDaCXp7rzql8tjEPNj7xWvvB6UDAiZLc+HjAmldOZqMYPesUwGeGyZ5HdJ/rdWajrJPaDbkb2lp5ZAXWiT+271ukJzgpInEh5Wsn98TlLTs37mBxr900Bv7jEB/QlQSwMEFAAAAAAA9XpVTAAAAAAAAAAAAAAAAAsAAABleHRlbnNpb25zL1BLAQIUAxQAAAAIAPV6VUx/xBZI                                                 'browserName' => 'firefox',
                                                 'browserVersion' => '',
                                                 'acceptInsecureCerts' => bless( do{\(my $o = 1)}, 'JSON::PP::Boolean' )
                                               }
                            },
          'desiredCapabilities' => {
                                     'acceptSslCerts' => bless( do{\(my $o = 1)}, 'JSON::PP::Boolean' ),
                                     'browserName' => 'firefox',
                                     'version' => '',
                                     'firefox_profile' => 'UEsDBBQAAAAIAPV6VUx/xBZIrwMAAOkMAAAHAAAAdXNlci5qc51XTW8bOQy991cUPm2BRnCSFmh3T9k0CyxQbIoaQY+CRuJ4FGskrURl7H9faj4axx7POL1lZFIkH8n3lBQhcB+g/GPRQKGCfqJvEWOqgSeLIUUExTUdQFi8f0sH8O6vN+nZSwkUAbwLqO2aeWe03LF8uEpFTX7a2TsrCgOK3Eth4oG/BWxc2LBaWLGGC1eWRlu4iCgwxXGXIriGvlgEU8bkc2yWgiHjxeKEpSih/TvnWAvTUMoMptJSribDLZdVcARFlEF75CFZjroG8rlenkqqrTmioxABWiBLuoPLIGI1XZDS0RuxA3V3uVz951DLHOnDuDGKIjIqxN7bW+MijF8NWwTbJsQK4+TG6IgzlcMTOmcigxBckOTpzD5YxyNQi0ABABGYglIkg9/oPLLcGHK4+nT1abaEew92PB9P4HmM2ZjXTgkznX7OfaORIRioAcOOdRe09lfjedDEbZijDLiFptFWuebYOOq1dZZaWkNdQFi1nzMTShdZ44Tqp5umo3LNjwrsipYmL8yce826dJhKtZ9swlB3v09DQBqp7DPqMoShogncYYVE4RL+WRhhN4tXr/q39vBGSugRP6tDkw19FE+iW7/J+vcGPXlKama/9251Hlu33Jt/7W038KMxhPdnXT4Ae/fw9YZdM/EMx/GdW6+JLIQxrKk0QZL3M8D/SYcpaurawMmNP0YO2xxAd+M4R9EVCINV901sFZ6IZVipQ8Tv6cQKHmNriZzK3UNsRWEOAUeaErQax/RZdSgHKN2W97Txefn5+mADQaagcUfZGqC/WMSgJXIX9Fpb3g3keD572tY2Y0/bJAQcx22QpgrRM1/pWO0u8s+e9PHCgF1j5vOrjx/Haw8gVN5AQJAU6J8M8Q31QM6sYwQRZNUjPV7OoJI0kJHRELiGFzvek+9rZyD5TFGTIv2SKTwxy3kLYKiCQKJ5nvULlT7PI9No8qwijc5Z8WHUWE0CbDN6i8zTARYnJ9q49fplwNOtoSN1b3+0lBwvl0zTFLmH71+neXPw7rs2U1IFxAWyArn50vXz7+6X02TQczxvFUzRYtg1zy0d9zjaosP1Ody6Q4wbMDK/iWb14lckGQftmhmXXzqc+xOsMMcyvMfBIqGbJaxs9KUDaCXp7rzql8tjEPNj7xWvvB6UDAiZLc+HjAmldOZqMYPesUwGeGyZ5HdJ/rdWajrJPaDbkb2lp5ZAXWiT+271ukJzgpInEh5Wsn98TlLTs37mBxr900Bv7jEB/QlQSwMEFAAAAAAA9XpVTAAAAAAAAAAAAAAAAAsAAABleHRlbnNpb25zL1BLAQIUAxQAAAAIAPV6VUx/xBZIrwMAAOkMAAAHAAAAAAAAAAEAAAC0gQAAAAB1c2VyLmpzUEsBAhQDFAAAAAAA9XpVTAAAAAAAAAAAAAAAAAsAAAAAAAAAAAAQAP1B1AMAAGV4dGVuc2lvbnMvUEsFBgAAAAACAAIAbgAAAP0DAAAAAA==',
                                     'javascriptEnabled' => $VAR1->{'desiredCapabilities'}{'acceptSslCerts'},
                                     'platform' => 'ANY'
                                   },
          'extra_capabilities' => {}
        }`
Response:
`{
          'sessionId' => undef,
          'cmd_status' => 'NOTOK',
          'cmd_return' => {
                            'error' => 'session not created',
                            'message' => 'Unable to find a matching set of capabilities',
                            'stackTrace' => 'stack backtrace:
   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e
   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46
   2:           0x4409a1 - webdriver::error::WebDriverError::new::h81babdd86c977032
   3:           0x441ab6 - geckodriver::marionette::MarionetteHandler::create_connection::hf0532ddb9e159684
   4:           0x428570 - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193
   5:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25
   6:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba
   7:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
   8:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473
   9:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:692
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84'
                          }
        }`

**Comment by teodesian** [comment]
Caps look fine, let's see what happens if I delete some of the compat

**Comment by teodesian** [comment]
Yep, it's choking on the compat layer
