### ISSUE TITLE
get_text() not working for element

### ISSUE THREAD

**Issue by tranwave** [teodesian/Selenium-Remote-Driver#373]
I'm trying to extract the text below "(The text I want)" with either get_text() from Selenium::Remote::WebElement or Selenium::Remote::Driver and it's not working. I'm trying to get it with this xpath //span[@class='wsItem']/text()
Any ideas?

<span class="wsItem">
 <span class="innerWsItem">Text Here
 </span>
 "(The text I want)"
</span>

**Comment by teodesian** [comment]
What version of S::R::D, what verison of driver(s), what browsers?

Anyways, supposing the text is like so:
`<span class='wslItem'>Text Here "(The text I want)"</span>`
You could do
`my ($text_i_want) = $driver->find_element('span.wslItem','css')->get_text() =~ m/(\(.*\))/;`

**Comment by teodesian** [comment]
closing this due to lack of response.
