### ISSUE TITLE
Couldn't retrieve command settings properly

### ISSUE THREAD

**Issue by mjegh** [teodesian/Selenium-Remote-Driver#374]
As far as I can tell nothing changed on this box which was happily working with S::R::D 1.24 and $Selenium::Remote::Driver::FORCE_WD2 = 1 and there are no auto updates or anything like that and we are using stratopan so I know we've not upgraded any modules.

As of today the scripts using S::R::D all die like this:

Couldn't retrieve command settings properly
 at /home/bet/perl5/perlbrew/perls/perl-5.24.2/lib/site_perl/5.24.2/Selenium/Remote/Driver.pm line 345.
 at /home/bet/perl5/perlbrew/perls/perl-5.24.2/lib/site_perl/5.24.2/Selenium/Remote/Driver.pm line 345.

This is debian Linux box
4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux

Google chrome is Version 61.0.3163.100 (Official Build) (64-bit)

As a developer myself I know how "nothing has changed" sounds so I'm assuming something has but I can't find it and I don't know enough about this module to diagnose the problem.

**Comment by mjegh** [comment]
Actually, it is happening when calling $driver->close.

**Comment by teodesian** [comment]
This sounds serious, can you include a quick script to reproduce?  What version of drivers/browsers are you using?

**Comment by mjegh** [comment]
Try as I might, I cannot reproduce this now. I tried a few things to debug it but reverting the code to where it was when I was getting this issue no longer shows the problem. By means close and if I can reproduce it I'll come back.

**Comment by teodesian** [comment]
Sounds good to me.  Feel free to re-open or file a new case if you can get it pinned down.
