### ISSUE TITLE
Error handler context

### ISSUE THREAD

**Issue by ylavoie** [teodesian/Selenium-Remote-Driver#378]
The error_handler could benefit from having the `@args` from `_execute_command` passed to provide error context. Then the user may be able to provide more focused messages.
The return value from the error_handler could also be used to indicate if the error was handled.

**Comment by teodesian** [comment]
That sounds pretty good -- I already beefed up the error messages which were previously being silently dropped in things like chromedriver.  I've actually shimmed in a way to keep the args in some of my code used at the firm to do stuff like re-execute in the case that an element detaches from the DOM.  Doing this would simplify that, so I'll look at implementing this.

**Comment by teodesian** [comment]
Thanks for the pull request.  I'll look at merging and adding POD and unit tests soon.
