### ISSUE TITLE
maximize_window() is not changing the window size in chrome

### ISSUE THREAD

**Issue by mpspahr** [teodesian/Selenium-Remote-Driver#380]
The window remains the same size when maximizing in chrome using the method maximize_window(). The problem appears to be related to this code in lib/Selenium/Remote/Driver.pm.

`if ($self->{is_wd3} && $self->browser_name eq 'chrome') {
    return $self->execute_script(qq{window.resizeTo(screen.availWidth,screen.availHeight); return 1;});
}`

Manually attempting to run window.resizeTo() in chrome also produces no results.

**Comment by teodesian** [comment]
Supposedly in Chromedriver 2.37 they implemented some more window methods from WC3, so maybe I won't need polyfills anymore:

* Implemented various window command endpoints from w3c spec
* Implemented get element rect endpoint from w3c spec

**Comment by mpspahr** [comment]
I tested the latest published 2.37 and latest 2.37 continuous from:
https://console.cloud.google.com/storage/browser/chromedriver-data/continuous?pli=1
by commenting out the code I noted above. Maximize was not working in either build.

Based on this issue it appears maximize hasn't been completed yet:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1940

**Comment by teodesian** [comment]
Dang.  Guess I will have to work on a better polyfill then.

**Comment by teodesian** [comment]
Aaaaand newest chromedriver just hangs forever on my chromium 64.0.3282.167.  I'll have to test using the older setup back at the office.

**Comment by teodesian** [comment]
One thing you can try passing as part of 'extra_capabilities':
`args => ['start-maximized'],`

**Comment by teodesian** [comment]
OK, so it looks like they disabled resizeTo because of abusive behaviors by advertisers.

https://stackoverflow.com/questions/3641648/the-javascript-resizeto-function-not-working-in-chrome-and-opera

This means I can't write a JS polyfill.  This also means we're screwed if you want to maximize; the only option is to fullscreen().

I'm looking at using set_inner_window_size as a workaround, but it falls down on any page that insta-alert()s.

**Comment by teodesian** [comment]
set_inner_window_size doesn't work either.  We're just hosed.

**Comment by mpspahr** [comment]
I ended up settling with using set_window_size() and passing in screen.availHeight and screen.availWidth as a temporary solution. The result is just short of maximizing but it ended up as a better solution for my current project.

**Comment by teodesian** [comment]
I was wanting to avoid a two-call polyfill, but I guess if it works, it works.  Will implement soon.
