### ISSUE TITLE
switch_to_frame / switch_to_parent_frame hangs if frame was deleted before

### ISSUE THREAD

**Issue by hornschorsch** [teodesian/Selenium-Remote-Driver#388]
Hi, i am using S::R::D 1.22, geckodriver 0.19.1, selenium-server-standalone-3.8.1 and firefox 55.0.3.

I have a silly webpage that uses iframes. I can switch into the iframe and do things there without problems.Finally a certain link inside the iframe is clicked, which causes the iframe to be closed and a complete new page without frames is loaded. If i try to switch back to the main frame then with

`$driver->switch_to_frame();`

it hangs for ever. I believe this is because `switch_to_frame` calls `switch_to_parent_frame` if the id passed to `switch_to_frame` is NULL, but the child frame does not exist any more and so it can not switch to the parent. I worked around this by calling:

`$driver->switch_to_frame(0);`

Besides that, is it correct that `switch_to_frame` calls `switch_to_parent_frame` if the id is NULL? If you have several frames nested into each other and you are at the third level, `switch_to_frame()`  will swich to the second level and not to the top.

**Comment by teodesian** [comment]
If we nest frames, you are correct that the old behavior is not preserved of going all the way back up the hierarchy.  That polyfill will have to be corrected, and the POD updated.

The solution might be as simple as assuming we go to frame 0, as if that's deleted we're in big trouble.

**Comment by teodesian** [comment]
ok, so SwitchToParentFrame is actually implemented by the drivers and not me.  If they aren't smart enough to implement the proper frame descent algorithm, I am loath to do it myself.

**Comment by hornschorsch** [comment]
I am sorry but i still believe it is wrong to call `switch_to_parent_frame` if $id is NULL. I now had another application where my workaround with `$driver->switch_to_frame(0);` did not work, for whatever reason (perhaps because the application works with two windows).

So i removed the line:
`return $self->switch_to_parent_frame() if ($self->{is_wd3} && !defined($id));`
from switch_to_frame in Driver.pm and changed my script back to call
`$driver->switch_to_frame();`
and now it works.

According to https://github.com/mozilla/geckodriver/issues/1270 there really is a bug in geckodriver but also according to https://w3c.github.io/webdriver/#switch-to-frame switch_to_frame should "Set the current browsing context to the current top-level browsing context." if id is NULL.

**Comment by teodesian** [comment]
The reason I'm doing that is to match JSONWire behavior, not WC3 behavior.  The whole idea here was to not break people's existing tests.

https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidframeparent

That said the reason you're probably running in to this is that many implementors did the JSONWire method incorrectly (matching the WC3 behavior).

So

A case can be made that this behavior should be controlled with a flag.  I'll go with that.

**Comment by teodesian** [comment]
Actually disregard the prior, I misread the spec!  This is a real bug.
