### ISSUE TITLE
Selenium::Firefox not working with firefox_binary

### ISSUE THREAD

**Issue by karstengit** [teodesian/Selenium-Remote-Driver#400]
I am trying to start working with https://metacpan.org/pod/Selenium::Firefox
I don't want to use the selenium server and i have installed this perl module and geckodriver.

Here is my testcode:
```#!/usr/bin/perl

use strict;
use warnings;
use Selenium::Firefox;

my $mech = Selenium::Firefox->new( 
	startup_timeout => 20,
	firefox_binary => '/srv/bin/firefox.54.0b13/firefox',
# 	binary => '/usr/local/bin/geckodriver',
# 	marionette_enabled => 1
);
$mech->get('http://www.google.com');
print $mech->get_context();
```

This script opens a blank new window of firefox and then **nothing** is happen.
No google is opened.
No further output.
When i look in the addons of this new window the selenium cannot be find - it is like a new blank installation.

How can i connect to an existing running firefox?
Where can i find some examples or an tutorial for this perl module?

**Comment by karstengit** [comment]
It is the same when i comment out **firefox_binary**.
Then a window of the standard distribution firefox in Debian (here V 52.9) is opened.
But again **nothing** is happen.

**Comment by karstengit** [comment]
O.K. No support here!

I could find out that i didn't wait enough.
The timeout was happening after 77 seconds with the error message
> Could not create new session:  at ./test.pl line 7.

So this is not a problem of the perl library - it is a problem of Firefox.
Not all versions seems to work for automatization.
Now i have tried Firefox 62.0 and it is working!

So this bug can be closed.

**Comment by teodesian** [comment]
Forgive the tardy reply, I've been out of the loop for roughly a week.

Unfortunately, yes, the problem much of the time is driver incompatibility across driver versions, or even straight up driver bugs.  This is increasingly common these days.
