### ISSUE TITLE
How to pass a zipped profile folder to new() ?

### ISSUE THREAD

**Issue by hornschorsch** [teodesian/Selenium-Remote-Driver#401]
Sorry for the stupid question, but how do i pass a zipped (and base 64 encoded) profile folder to Selenium::Remote::Driver->new() ?

The manpage says:
firefox_profile    - Profile    - Use Selenium::Firefox::Profile to create a Firefox profile for the browser to use.  Optionally can pass a base64'd zip data of  a profile directory if you don't like Selenium::Firefox::Profile.

but this script does not work:

$driver = Selenium::Remote::Driver->new(
    'firefox_profile' => $profile,
);

coercion for "firefox_profile" failed: firefox_profile should be a Selenium::Firefox::Profile

**Comment by teodesian** [comment]
I've got an example in one of the unit tests, I'll try and dig it up tonight

**Comment by teodesian** [comment]
and more importantly add it to the POD

**Comment by teodesian** [comment]
https://github.com/teodesian/Selenium-Remote-Driver/blob/master/t/Firefox-Profile.t

Working on updating POD...

**Comment by teodesian** [comment]
It's gotta go in extra_capabilities
