### ISSUE TITLE
Installation on Windows fails due to dependency on Test::Time

### ISSUE THREAD

**Issue by Qarj** [teodesian/Selenium-Remote-Driver#410]
As far as I can make out, `Test::Time` time fails to install on Windows with Strawberry Perl since version 0.06. Current version is 0.07.

I managed to work around by manually installing v0.05 of `Test::Time` from https://github.com/manwar/Test-Time/releases

I'm not sure if it is possible to remove the dependency on `Test::Time`?

**Comment by teodesian** [comment]
Sure it's possible.  Just means I need to do more industrial strength mocking in the test files.

I'll look at it soon.

**Comment by Chaoui05** [comment]
I got the same issue. I cannot go further and i cannot install Selenium::Remote::Driver due to this prerequisite
Could you please advise ? Thx

**Comment by Chaoui05** [comment]
Thanks Qarj i will have a look to see if it suits my needs. Pending the fix of Mr Teo

**Comment by Chaoui05** [comment]
@Qarj I don't undesrtand following steps
3.CD to the folder with Makefile.pl, then run it
4. cpan .

**Comment by Qarj** [comment]
@Chaoui05 Once you have the archive fully unzipped, you'll find a folder with Makefile.pl, so you need to CD to that fold from the command prompt and type `Makefile.pl`  then press enter

For step 4, type `cpan .` then press enter

**Comment by Chaoui05** [comment]
Thanks @Qarj 

Looks like good
