### ISSUE TITLE
Impossible to launch an easy Perl script

### ISSUE THREAD

**Issue by Chaoui05** [teodesian/Selenium-Remote-Driver#412]
Hi all,

I am trying to execute this simple perl test script.
```perl
#!/usr/bin/perl`
use strict;
use warnings;
use Selenium::Remote::Driver;

my $driver = Selenium::Remote::Driver->new;
$driver->get("http://www.google.com");
```

The one in the sypnosis but i am facing the following issue : 

> Could not create new session: Server returned error message read timeout at C:/Strawberry/perl/vendor/lib/Net/HTTP/Methods.pm line 268.
 instead of data at TEST1.pl line 7.

Thanks in advance for the support

**Comment by tod222** [comment]
S::R::D needs the Selenium Server to be running already. The example won't run as-is.

It's simpler to run Selenium::Firefox or equivalent for another browser, as then you don't have to worry about the Java server.

**Comment by Chaoui05** [comment]
> S::R::D needs the Selenium Server to be running already. The example won't run as-is.
> 
> It's simpler to run Selenium::Firefox or equivalent for another browser, as then you don't have to worry about the Java server.

Thanks for the answer @tod222 
But i already 

> PS C:\Users\user1\node_modules\selenium-server-standalone-jar\jar> java -jar selenium-server-standalone-3.14.0.
jar -role hub
14:24:25.584 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.14.0', revision: 'aacccce0'
14:24:25.584 INFO [GridLauncherV3$2.launch] - Launching Selenium Grid hub on port 4444
2018-11-05 14:24:26.055:INFO::main: Logging initialized @1176ms to org.seleniumhq.jetty9.util.log.StdErrLog
14:24:26.469 INFO [Hub.start] - Selenium Grid hub is up and running
14:24:26.479 INFO [Hub.start] - Nodes should register to http://10.132.5.117:4444/grid/register/
14:24:26.479 INFO [Hub.start] - Clients should connect to http://10.132.5.117:4444/wd/hub

**Comment by teodesian** [comment]
In your example above, I notice you aren't providing a path to any driver binaries.  Gonna be hard to interact with any browser without that.
`-Dwebdriver.chrome.driver=/path/to/your/chromedriver`
`-Dwebdriver.gecko.driver=/path/to/your/geckodriver`
Would be the JAR options you are probably missing.

**Comment by Chaoui05** [comment]
> In your example above, I notice you aren't providing a path to any driver binaries. Gonna be hard to interact with any browser without that.
> `-Dwebdriver.chrome.driver=/path/to/your/chromedriver`
> `-Dwebdriver.gecko.driver=/path/to/your/geckodriver`
> Would be the JAR options you are probably missing.
> 
> You are also running in a hub configuration. Generally if you don't connect nodes to that, it won't work either.

Thank you dear @teodesian teodesian. I can imagine how you are busy so thanks for the support.
First i removed the hub configuration.
A last thing please . Where i use to put this 
```
-Dwebdriver.chrome.driver=path
```

In my perl code ?!

Thx

**Comment by teodesian** [comment]
That's part of your invocation of the webdriver JAR.  E.G.

`java -Dwebdriver.gecko.driver=geckodriver -jar selenium-server-standalone-3.14.0.jar`

**Comment by Chaoui05** [comment]
> That's part of your invocation of the webdriver JAR. E.G.
> 
> `java -Dwebdriver.gecko.driver=geckodriver -jar selenium-server-standalone-3.14.0.jar`

Thx but I already did it @teodesian George as you can see here in my shell...
```  shell
PS C:\Users\user1\node_modules\selenium-server-standalone-jar\jar> java -Dwebdriver.chrome.driver=C:\Users\user1\Downloads\chromedriver_win32 -jar selenium-server-standalone-3.14.0.jar
Error: Could not find or load main class .chrome.driver=C:\Users\user1\Downloads\chromedriver_win32
```

**Comment by teodesian** [comment]
`Error: Could not find or load main class  .chrome.driver=C:\Users\user1\Downloads\chromedriver_win32`
That's a hint that your invocation is incorrect.  For some reason the args are being parsed such that it believes you are specifying the main class file as
 `.chrome.driver=C:\Users\user1\Downloads\chromedriver_win32`.
This likely means you need to escape your specification of the path to the chromedriver, e.g.
`java -Dwebdriver.chrome.driver="C:\Users\user1\Downloads\chromedriver_win32" -jar selenium-server-standalone-3.14.0.jar`

**Comment by teodesian** [comment]
Maybe? It should rule out any kind of arg parsing issues if you put it in the same dir and invoke more simply.

Some java versions are also picky about where you put the -D options; you may have to stick those arguments after the -jar argument.

**Comment by Chaoui05** [comment]
I tried all your suggestions but it still doesn't work. Still exactly the same issue...
I really don't understand what is wrong because if i execute the Selenium standalone server this one is up and running on the good port. 

I really don't know what to do

But Thank you again for the time you spent on my issue

**Comment by teodesian** [comment]
So it sounds like if you execute

`java -jar selenium.jar`

the server comes up fine, right?

But that doesn't really help you any as it doesn't know how to talk to any browser in that state.  You have to tell it where a browser driver binary is for it to talk to a browser.

That's what the -D options I've been asking you to pass are all about.  Your trouble is that you seem unable to get java to correctly accept the -D options you are passing; it appears that there's some trouble with the way they're being parsed by java on the command line.

Is it possible `java` has been aliased as a command to something which is interfering with your arg parsing?  The errors you are getting imply it is ignoring your -jar directive and instead attempting to execute a fragment of the -D option as the main java class to execute.

Normally when java executes, you pass it a class to execute, unless you pass a -jar.  It is acting as though in this manner despite you passing -jar.  That is quite abnormal, and there's something either going on with:

1. your java interpreter, it may need reinstall/upgrade/etc
2. your command environment (aliases, bad escaping, etc)

You may try the example I provided earlier, but using single instead of double quotes?  Sometimes MSWin is picky about that stuff too.

**Comment by Chaoui05** [comment]
> So it sounds like if you execute
> 
> `java -jar selenium.jar`
> 
> the server comes up fine, right?
> 
> But that doesn't really help you any as it doesn't know how to talk to any browser in that state. You have to tell it where a browser driver binary is for it to talk to a browser.
> 
> That's what the -D options I've been asking you to pass are all about. Your trouble is that you seem unable to get java to correctly accept the -D options you are passing; it appears that there's some trouble with the way they're being parsed by java on the command line.
> 
> Is it possible `java` has been aliased as a command to something which is interfering with your arg parsing? The errors you are getting imply it is ignoring your -jar directive and instead attempting to execute a fragment of the -D option as the main java class to execute.
> 
> Normally when java executes, you pass it a class to execute, unless you pass a -jar. It is acting as though in this manner despite you passing -jar. That is quite abnormal, and there's something either going on with:
> 
> 1. your java interpreter, it may need reinstall/upgrade/etc
> 2. your command environment (aliases, bad escaping, etc)
> 
> You may try the example I provided earlier, but using single instead of double quotes? Sometimes MSWin is picky about that stuff too.

Thaaank you George very much for all your help and your support, i finally found the issue 
the quote have to begin just after calling the java command as follows

```
java "-Dwebdriver.chrome.driver=C:\Users\user1\node_modules\selenium-server-standalone-jar\jar\chromedriver.exe" -jar selenium-server-standalone-3.14.0.jar
```
Here is the link where i found the answer : 
[https://stackoverflow.com/questions/51370164/java-error-could-not-find-or-load-main-class-ie-driver-with-selenium](url)

As you suggested just now,it came from the second option : 

> your command environment (aliases, bad escaping, etc)
You may try the example I provided earlier, but using single instead of double quotes? Sometimes MSWin is picky about that stuff too.

I just have to thank you a lot for all your support and the time you took to give your feedback, much appreciated. If a day i am in Texas, i will come to say you hi !

**Comment by teodesian** [comment]
Glad to be of help!  Happy testing.
