### ISSUE TITLE
Patch for taking full screenshots

### ISSUE THREAD

**Issue by hornschorsch** [teodesian/Selenium-Remote-Driver#419]
On https://github.com/mozilla/geckodriver/releases i found that geckodriver 0.24 now supports taking full screenshots. `$d->capture_screenshot()` until now only created an image of the visible part of the page.
I made a small patch that makes `capture_screenshot()` take a full screenshot if a second parameter `{'full' => 1}` is passed in.

[patch.txt](https://github.com/teodesian/Selenium-Remote-Driver/files/2937951/patch.txt)

**Comment by teodesian** [comment]
patch does not apply cleanly

mind making a PR instead?

**Comment by hornschorsch** [comment]
Sorry for the late answer, here is the same patch for the current 1.31 release.

[patch-1.31.txt](https://github.com/teodesian/Selenium-Remote-Driver/files/3257656/patch-1.31.txt)

**Comment by teodesian** [comment]
Thanks, I'll try and get it in before I release this morning!

**Comment by teodesian** [comment]
https://github.com/teodesian/Selenium-Remote-Driver/commit/88880d90e86481683a55ad3a6db0264538e90c86
