### ISSUE TITLE
Could not create new session: Server returned error code 500 and no data

### ISSUE THREAD

**Issue by tomas-zemres** [teodesian/Selenium-Remote-Driver#420]
When I try to create driver instance it raises error:
 "Could not create new session: Server returned error code 500 and no data"
```
my $driver = Test::Selenium::Remote::Driver->new(
  'browser_name' => 'firefox',
  'remote_server_addr' => $host,
  'base_url' => $base_url,
  'port' => 4444,
  'auto_close' => 0,
  'javascript' => 1
);
```

I am using Selenium::Remote::Driver 1.30
Selenium server "version": "3.141.59"

I debug the problem and find the bug / solution:

There are two workarounds:

   1) If I use `Selenium::Remote::Driver->new` instead of `Test::Selenium::Remote::Driver->new` then the instance is successfully created.

   2) If I put `version => ''` to constructor `Test::Selenium::Remote::Driver->new` then the instance is successfully created.

There is probably problem in `Test::Selenium::Remote::Driver::BUILDARGS`:
 https://github.com/teodesian/Selenium-Remote-Driver/blob/master/lib/Test/Selenium/Remote/Driver.pm#L128
there is attribute version set to undef even if it is missing in constructor, but default "version" should be empty string "" (defined as attribute default here https://github.com/teodesian/Selenium-Remote-Driver/blob/master/lib/Selenium/Remote/Driver.pm#L562)

**Comment by tomas-zemres** [comment]
It is probably related to issue https://github.com/teodesian/Selenium-Remote-Driver/issues/409
but I do not understand why the 409 has been closed.

**Comment by teodesian** [comment]
409 was closed because it got fixed by another patch.  Long story short, the webdriver 3 spec changed out from under us to match the way JSONWire used to do things because the driver implementors didn't want to bother with doing things the new way.

What this probably means is they've changed the spec again.  Yay.

**Comment by teodesian** [comment]
Getting 

```Could not create new session: Null values found in w3c capabilities. Keys are: [browserVersion] at test.pl line 8.```

today. humm
