### ISSUE TITLE
is_selected does not work on select elements

### ISSUE THREAD

**Issue by royerboat** [teodesian/Selenium-Remote-Driver#426]
Trying to execute "is_selected" on a select html element does not give you the selected element. This seems to be because we are checking for the "checked" property instead of the "selected" property in the code (https://github.com/teodesian/Selenium-Remote-Driver/blob/master/lib/Selenium/Remote/WebElement.pm#L248).

**Comment by teodesian** [comment]
This is an incomplete shim -- is_selected meant the same thing as is_checked in JSONWire, and I forgot about the other usage.  Good catch, thanks.  Will fix soon.

**Comment by teodesian** [comment]
A select element you should get the value of to find which option is selected.

This is only the relevant in the case you are looking directly at an <option> to see the selected() property.
