### ISSUE TITLE
Error while executing command: unknown error: 'ms' must be a double

### ISSUE THREAD

**Issue by tim-2** [teodesian/Selenium-Remote-Driver#427]
set_timeout() causes the following error:

```
 Error while executing command: unknown error: 'ms' must be a double
  (Session info: chrome=63.0.3239.108)
  (Driver info: chromedriver=2.33.506092 (733a02544d189eeb751fe0d7ddca79a0ee28cce4),platform=Linux 4.15.0-52-generic x86_64) at /home/tim/perl5/perlbrew/perls/perl-5.28.0/lib/site_perl/5.28.0/Selenium/Remote/Driver.pm line 403.
 at /home/tim/perl5/perlbrew/perls/perl-5.28.0/lib/site_perl/5.28.0/Selenium/Remote/Driver.pm line 353.
```

If I change this* line from
`my $params = { $type     => $ms };`
to
`my $params = { type     => $type, ms => $ms };`
the error is gone.

*https://github.com/teodesian/Selenium-Remote-Driver/blob/master/lib/Selenium/Remote/Driver.pm#L1583

**Comment by Deracination** [comment]
This could be due to the selenium web driver jar not being the right version? Unfortunately I can't verify this since after upgrading to latest selenium-standalone.jar and chromedriver my selenium tests freeze up!

**Comment by teodesian** [comment]
Yeah, I had another filing along this line.

Good old chrome/chromedriver being broken in exciting ways as usual and it being my fault somehow

**Comment by teodesian** [comment]
seems to work on latest chromedriver.  good enough
