### ISSUE TITLE
Selenium::Firefox not re-entrant, using same marionette port for multiple instances

### ISSUE THREAD

**Issue by hornschorsch** [teodesian/Selenium-Remote-Driver#432]
Hi,

when using Selenium::Firefox and starting more than one session at a time, the marionette portnumber which is passed to geckodriver is always the default number of 2828. I could fix this by replacing `$self->marionette_binary_port` with `$self->marionette_port`in line 45 in Firefox.pm

**Comment by teodesian** [comment]
Good catch, will implement

**Comment by teodesian** [comment]
Hmm, it's not as simple to simply use port()? I think I may have to choose a new port in another range much as is done in CanStartBinary's port definition routine.

I'll have to investigate this a bit more to be sure what the fix is.

**Comment by hornschorsch** [comment]
Indeed it does not work in all situations. I believe the problem is with `find_open_port_above()` in `CanStartBinary/ProbePort.pm`. It starts at the given port number (2828 in this case) and tries to connect to that port. If that fails it assumes the port is free and returns that number, but i believe this can lead to race conditions.

A better way would probably be to ask the OS for a free portnumber by `bind()`ing to port 0. That´s how geckodriver does it too, if no portnumber is given on the commandline.

I rewrote `find_open_port_above()` as follows and it seems to work for me:
```
sub find_open_port_above {
    socket(SOCK, PF_INET, SOCK_STREAM, getprotobyname("tcp"));
    bind(SOCK, sockaddr_in(0, INADDR_ANY));
    my $port = (sockaddr_in(getsockname(SOCK)))[0];
    close(SOCK);
    return $port;
}   
```

**Comment by teodesian** [comment]
Looks like a good patch, I'll put that in.  Thanks

**Comment by hornschorsch** [comment]
Thanks, but i am afraid you forgot to change Firefox.pm accordingly
```
$ diff -c Firefox.pm.org Firefox.pm     
*** Firefox.pm.org      Tue Oct 22 09:11:02 2019
--- Firefox.pm  Tue Oct 22 09:11:38 2019
***************
*** 42,48 ****
                  ' --port '
                . $self->port
                . ' --marionette-port '
!               . $self->marionette_binary_port
                . ' --binary "'
                . $self->firefox_binary . '"';
  
--- 42,48 ----
                  ' --port '
                . $self->port
                . ' --marionette-port '
!               . $self->marionette_port
                . ' --binary "'
                . $self->firefox_binary . '"';
```

**Comment by teodesian** [comment]
I see now.  patching...

**Comment by teodesian** [comment]
c7d35d66be0dff5ad037608afb552c16dde81c1a
