### ISSUE TITLE
Chrome browser gets closed with auto_close set to 0

### ISSUE THREAD

**Issue by inpbox** [teodesian/Selenium-Remote-Driver#438]
Environment:
* $Selenium::Chrome::VERSION = '1.36';
* $Selenium::Remote::Driver::VERSION = '1.36';
* $Selenium::CanStartBinary::VERSION = '1.36';
* Chrome version 79, ChromeDriver 79.0.3945.36
* Debian 10/Buster

Issue:
* Chrome closes after Perl script ends, despite auto_close 0 being set

Debug:
I've tracked the problem to module:
* Selenium::CanStartBinary::shutdown_binary

The problem in: shutdown_binary is the following line: 
* $ua->get( 'http://127.0.0.1:' . $port . '/wd/hub/shutdown' );

This will shutdown the chromedriver + Chrome browser.

Example:
```
#!/usr/bin/perl

use 5.018;
use Selenium::Chrome;

my $driver = Selenium::Chrome->new('auto_close'=>0);
$driver->get('https://google.com');
say $driver->get_title();
```

**Comment by teodesian** [comment]
chromedriver probably changed the way they expect this parameter to be set again.  I'll poke at it this weekend

**Comment by teodesian** [comment]
ok, so as the reporter suggested, this is caused by shutdown_binary.

we will have to remove that from the destructor in the event auto_close = 0.

**Comment by teodesian** [comment]
hmm this should actually be fine
sub shutdown_binary {
    my ($self) = @_;

    if ( $self->auto_close && defined $self->session_id ) {
        $self->quit();
    }
...

Guessing something else is going on like I originally suspected

**Comment by teodesian** [comment]
could be session_id dead

**Comment by teodesian** [comment]
bad logic in shutdown_binary
