### ISSUE TITLE
Windows filepaths cause test failure

### ISSUE THREAD

**Issue by dylanstreb** [teodesian/Selenium-Remote-Driver#439]
I'm getting a test failure on Windows when I try to install Selenium::Remote::Driver 1.36 through cpan. I'm using Perl v5.30.1, x64, self compiled. I'm running cpan through a powershell terminal instead of cygwin or cmd.exe.

```
t\01-driver.t .. 1/?
#   Failed test 'find_element croaks properly'
#   at t\01-driver.t line 300.
#                   'An element could not be located on the page using the given search parameters: element_that_doesnt_exist,id at t\01-driver.t line 298.'
#     doesn't match '(?^:An element could not be located on the page using the given search parameters: element_that_doesnt_exist,id at t\01-driver.t line 298)'
t\01-driver.t .. 88/? # Looks like you failed 1 test of 124.
t\01-driver.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/124 subtests
        (less 19 skipped subtests: 104 okay)
```

The backslash from the Windows filepath appears to be breaking the regex, treating \0 as an escape sequence rather than literal characters. All other tests pass. 

I believe the fix is to just wrap the regex in \Q \E to treat potential backslashes as literals. This fixes the issue locally. I haven't tested it on Linux or any other platform but I don't believe this change would cause any issues.

**Comment by teodesian** [comment]
Thank you for your contribution.  I'll do some more testing, and try to release a new version tonight.
