### ISSUE TITLE
ActionChain's key_down() is sending both a keyDown and keyUp

### ISSUE THREAD

**Issue by randyl** [teodesian/Selenium-Remote-Driver#442]
The `key_down()` method in `Selenium::ActionChains` is documented as 

> Sends key presses only, without releasing them

However, it's implemented by calling `send_keys_to_active_element()` in the driver. That method performs both a keyDown and keyUp for each key.

The `key_up()` method has the same problem.

For now, I've been able to perform a key_down by using `general_action()` in the driver, like so:
```
# Perform key_down for SHIFT
$driver->general_action( actions => [ { type => 'key', id => 'key', actions => [ { type => 'keyDown', value => KEYS->{'shift'} } ] } ] );
```

**Comment by teodesian** [comment]
I've got a patch on the issue-442 branch, but it needs testing.  Will look at soon

**Comment by teodesian** [comment]
Selenium::Remote::WDKeys::looks to work now, patches pushed up
