### ISSUE TITLE
Documentation for general_action() is out of date

### ISSUE THREAD

**Issue by randyl** [teodesian/Selenium-Remote-Driver#443]
The documentation for `general_action` in the driver says this:

> key => A raw keycode or character from the keyboard if this is a key event

I think it should be "value" instead of "key".

Using "key":
```
$driver->general_action( actions => [ { type => 'key', id => 'key', actions => [ { type => 'keyDown', key => KEYS->{'shift'} } ] } ] );
```
Produced this error:
```
'value' must be a single Unicode code point
```
Switching "key" to "value" worked:
```
$driver->general_action( actions => [ { type => 'key', id => 'key', actions => [ { type => 'keyDown', value => KEYS->{'shift'} } ] } ] );
```

**Comment by teodesian** [comment]
Will update.

**Comment by teodesian** [comment]
Looks like yet another case where the driver authors don't GAF about the standard:
https://www.w3.org/TR/webdriver1/#general-actions

Tell ya what, I'll keep hewing to the standards and just make a shim to pass 'value' to brain-damaged browser drivers.

**Comment by teodesian** [comment]
of course it's chromedriver that's the culprit.  How could I ever have guessed

**Comment by teodesian** [comment]
In their defense, firefox now also bad:
```Error while executing command: invalid argument: data did not match any variant of untagged enum KeyActionItem at line 1 column 80 at lib/Selenium/Remote/Driver.pm line 893```
