### ISSUE TITLE
switch_to_frame now gives 'id' can not be string error

### ISSUE THREAD

**Issue by Stringer26** [teodesian/Selenium-Remote-Driver#445]
On a recent chrome (80.0.3987.149) and perl v5.30.2 the command 
$driver->switch_to_frame(..string..)
now gives an error:
```
Error while executing command: invalid argument: invalid argument: 'id' can not be string
  (Session info: chrome=80.0.3987.149) at /usr/local/share/perl5/5.30/Selenium/Remote/Driver.pm line 403.
 at /usr/local/share/perl5/5.30/Selenium/Remote/Driver.pm line 353.
```
On another computer with an older version of perl  v5.16.3 and chrome (80.0.3987.122) everything is fine.

**Comment by Stringer26** [comment]
A work-around is to do
`$driver->switch_to_frame($driver->find_element_by_id(..string..))`
This works fine but the documentation for switch_to_frame still needs fixing.

**Comment by teodesian** [comment]
So, we should note that chrome as usual breaks the standard?  They do that at random every other build.
