### ISSUE TITLE
Selenium::Chrome shutdown_binary not closing ChromeDriver and Chrome processes

### ISSUE THREAD

**Issue by kevinpthorne** [teodesian/Selenium-Remote-Driver#448]
I recently rolled browser testing into our framework and it does wonders. The only issue we are finding is it seems like `shutdown_binary` is ignored when the server is under load. At the end of our deployments, we can have loads of `chrome` and `chromedriver` processes left.

"Under load" means we're running browser tests concurrently for different flavors of our framework. Maybe that is why `shutdown_binary` does not work? Are the `chromedriver` processes and subsequent `chrome` processes not forked from the test perl file? Any help would be much appreciated.

Here's a simplified test case:
```perl
our $BROWSER; # this is set in another file

&setup();
&test();
&teardown();

sub setup {
        # framework is being hosted locally already
	&testutil_bootWebFramework();

	our $USER = $main::_GLOBAL{'settings'}{'default_user'};
	our $PASS = $main::_GLOBAL{'settings'}{'default_user_password'};

	our $LOGIN_FORM_USERNAME_ID = "login-form-username";
	our $LOGIN_FORM_PASSWORD_ID = "login-form-password";

        # this is also usually done in the other file, but shown here for config.
        use Selenium::Chrome;
	$main::BROWSER = Selenium::Chrome->new(
		'extra_capabilities' => {
			'goog:chromeOptions' => {
				'args' => ['headless', 'no-sandbox', 'disable-gpu'] 
                                                # I know no-sandbox is bad, we're fixing it soon
			}
		}
	);
}

sub test {
	ok( $main::USER, "Default User found ($main::USER)" );
	ok( $main::PASS, "Default Pass found" );

        $main::BROWSER->get("https://$main::DOMAIN/login.html");
	## Do login via send_keys_to_active_element

	ok( &browser_verifyBase( $main::BROWSER, '/admin/' ),
		"Admin base href tag found" )
	  or $main::BROWSER->capture_screenshot( __FILE__ . ".png" );
}

sub teardown {
	$main::BROWSER->shutdown_binary;
}
```

**Comment by teodesian** [comment]
It could be chromedriver is not reaping it's children when it gets sent SIGKILL.

Are the leftovers zombies?  I would assume so.  If not that means chromedriver is orphaning it's chrome processes, which is even worse and harder to clean up.

**Comment by kevinpthorne** [comment]
No, the leftover processes are all sleeping.

![image](https://user-images.githubusercontent.com/8848627/80986772-448c4e00-8dee-11ea-867e-e632a5d939d2.png)

![image](https://user-images.githubusercontent.com/8848627/80987100-c9776780-8dee-11ea-9a00-65a480f38ebc.png)

In my testing, when `prove` is successful (no errors), the chrome* processes are closed just fine. However, if there is an error, my `teardown` is never called, even if I make my test like so:

```perl
&setup();
&test();
&teardown();


############ End required for tests

sub setup {
        $main::BROWSER = &createChromeBrowser();
}

sub test {
        $main::BROWSER->set_window_size( 1920, 1080 );
        $main::BROWSER->get("https://$main::DOMAIN/mypage");


        my $cookie = $main::BROWSER->get_cookie_named('i_dont_exist') or &teardown();
        ok( $cookie );
}

sub teardown {
        $main::BROWSER->shutdown_binary;
}
```
This is another test checking for a cookie on page `/mypage`. `get_cookie_named` throws and error about the non-existent cookie but never calls `teardown`, even when I "force it to" with the `or`.

**Comment by hornschorsch** [comment]
I experienced the same, a simple script:

```
use Selenium::Chrome;
$driver = Selenium::Chrome->new();
$driver->get("https://manitu.koblenz-net.de/");
print "press enter: "; <>;
$driver->close();
$driver->quit();
```

leaves a chromedriver process behind. Chrome itself is closed but the driver stays...

`horn      4783  0.1  0.1 426512 11500 pts/0    Sl   18:30   0:00 /usr/bin/chromedriver --port=55733 --url-base=wd/hub`

**Comment by teodesian** [comment]
We are already using a pretty nuclear option here to kill the driver binary -- we're sending it SIGTERM.

The way we figure out the PID is kinda irritating because it daemonizes instantly under a different PID than what we spawn it as.  So we have to do lsof on the port to figure out which chromedriver is listening on that port so we can whack the correct one and not every one of them.

If any of these drivers have stopped listening for whatever reason (likely because we call shutdown via the wc3 webdriver methods that SHOULD WORK BUT DO NOT because chromedriver is a joke)

We could just go nuclear and SIGTERM these mutts immediately and give the finger to the "official" way to shutdown the binary.  But then it won't shut down the browser and leave zombie browsers.

You can't win.  Guess what I do.  I don't use direct driver because of this -- I just dockerized my selenium head a long time ago and don't care anymore.

**Comment by PenelopeFudd** [comment]
Instead of using lsof and parsing it, we could use 'fuser -k 12345/tcp',
part of the 'psmisc' package: https://gitlab.com/psmisc/psmisc 

But fixing chromedriver would be the best solution, yeah. 

On 2020-06-04 04:22 PM, George S. Baugh wrote:

> We are already using a pretty nuclear option here to kill the driver binary -- we're sending it SIGTERM. 
> 
> The way we figure out the PID is kinda irritating because it daemonizes instantly under a different PID than what we spawn it as. So we have to do lsof on the port to figure out which chromedriver is listening on that port so we can whack the correct one and not every one of them. 
> 
> If any of these drivers have stopped listening for whatever reason (likely because we call shutdown via the wc3 webdriver methods that SHOULD WORK BUT DO NOT because chromedriver is a joke) 
> 
> We could just go nuclear and SIGTERM these mutts immediately and give the finger to the "official" way to shutdown the binary. But then it won't shut down the browser and leave zombie browsers. 
> 
> You can't win. Guess what I do. I don't use direct driver because of this -- I just dockerized my selenium head a long time ago and don't care anymore. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

-- 
Charles Howes  

Links:
------
[1]
https://github.com/teodesian/Selenium-Remote-Driver/issues/448#issuecomment-639167620
[2]

**Comment by kevinpthorne** [comment]
Good to know that this is a ChromeDriver issue instead of an issue with the module.

> You can't win. Guess what I do. I don't use direct driver because of this -- I just dockerized my selenium head a long time ago and don't care anymore.

I was thinking a similar solution would solve this.
