### ISSUE TITLE
Impossible to enable performance logging in chromedriver in WD3 (WD2 is ok) goog:loggingPrefs is ignored

### ISSUE THREAD

**Issue by mk654321** [teodesian/Selenium-Remote-Driver#449]
When using Chrome over WD2 I am able to enable performance logging. This is not possible if using WD3. 

It looks like goog:loggingPrefs is ignored in extra_capabilities.
```
my %settings = (

  'binary' => $chrome_driver_path,

  'extra_capabilities' =>{
      'goog:loggingPrefs' => {
          'performance' => 'ALL',
      },
      'goog:chromeOptions' => {
          'perfLoggingPrefs' => {
              'traceCategories' => 'performance',
          },
      },
  }
);
$driver = Selenium::Chrome->new(%settings);
```
Following error is thrown:

`Could not create new session: invalid argument: perfLoggingPrefs specified, but performance logging was not enabled `
See the attached file for full script.
[goog_loggingPrefs.txt](https://github.com/teodesian/Selenium-Remote-Driver/files/5319529/goog_loggingPrefs.txt)

What I've notice id this could be fixed by adding `'goog:loggingPrefs',` at the end of line 117 of Selenium/Remote/Spec.pm

**Comment by teodesian** [comment]
so, essentially adding it to the _caps array.  Ok, sounds good.

**Comment by mk654321** [comment]
Thank you.
