### ISSUE TITLE
What do you mean by «using Javascript directly to automate the testing of webpages» ?

### ISSUE THREAD

**Issue by tuxayo** [teodesian/Selenium-Remote-Driver#453]
README:
> Even then you are probably shooting yourself in the foot not using Javascript directly to automate the testing of webpages.

Which toolset(s) are you referring to? I don't know the JS testing ecosystem and your advice picked my interest. That might also help others wanting to follow and migrate away as you suggest to.

**Comment by teodesian** [comment]
Consider using Playwright

https://metacpan.org/pod/Playwright  - Is a perl interface I made for this because I'm sick of how horrid and unreliable selenium is

**Comment by tuxayo** [comment]
Thanks, so you where referring to using Playwright directly in JS and if not, use it via the Perl binding lib?

**Comment by teodesian** [comment]
yup
