### ISSUE TITLE
Test::MockModule is needed for tests

### ISSUE THREAD

**Issue by yuki-kimoto** [teodesian/Selenium-Remote-Driver#456]
Test fail Selenium-Remote-Driver-1.38.

<pre>
t/01-driver-pac.t ....................... ok
Can't locate object method "redefine" via package "Test::MockModule" at t/01-driver.t line 138.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 14.
</pre>

Maybe Test::MockModule is needed.

Can I pull request to add latest Test::MockModule to cpanfile?

**Comment by teodesian** [comment]
You can always make a pull request :)

I will look at the testsuite as suggested by #455 before the week is up.

**Comment by yuki-kimoto** [comment]
I created pull request.

https://github.com/teodesian/Selenium-Remote-Driver/pull/457

If you think ok, please merge.

**Comment by teodesian** [comment]
merged.
