### ISSUE TITLE
Selenium::Firefox warning Use of uninitialized value $path

### ISSUE THREAD

**Issue by yuki-kimoto** [teodesian/Selenium-Remote-Driver#461]
I get warning message.

<pre>
Use of uninitialized value $path in -e at C:/Strawberry/perl/site/lib/Selenium/CanStartBinary/FindBinary.pm line 48.
</pre>

The following code work well. but the above warning occur. 

<pre>
use strict;
use warnings;
use Selenium::Firefox;

# ドライバを生成。
my $driver = Selenium::Firefox->new;

# 何かを行う
$driver->get('http://www.google.com');
print $driver->get_title();

# ドライバをシャットダウンする
$driver->shutdown_binary;
</pre>

<pre>
$Selenium::Remote::Driver::VERSION = '1.39';
</pre>

<pre>
This is perl 5, version 32, subversion 1 (v5.32.1) built for MSWin32-x64-multi-thread

Strawberry Perl(Windows)
</pre>

<pre>
C:\Strawberry\perl\bin\geckodriver.exe
</pre>

**Comment by teodesian** [comment]
_validate_manual_binary looks like it's being called for some reason, _naive_find_binary is what should occur.  Probably bad fallback logic in the callers.

Thanks for the report, I'll look into it.
