### ISSUE TITLE
Selenium::Edge returns "could not create new session"

### ISSUE THREAD

**Issue by nck974** [teodesian/Selenium-Remote-Driver#463]
I get the following error:
Could not create new session: invalid argument: cannot parse capability: browserVersion
I have tried to change this lines in the driver:
`    if ( $self->isa('Selenium::Firefox') || $self->isa('Selenium::Chrome') ) {`
for this one 
    if ( $self->isa('Selenium::Firefox') || $self->isa('Selenium::Chrome') || $self->isa('Selenium::Edge') ) {
and it seems to work although it pins edge to my navigation bar I don't know why.

**Comment by teodesian** [comment]
Likely has to do with me not releasing the changes which make Edge.pm compatible with the new chrome-based version of MicrosoftEdge.

https://github.com/teodesian/Selenium-Remote-Driver/commit/b92685715ff5a0b9433a09157fbef37b5d1a0c5f

I'll make a release to CPAN soon.

**Comment by teodesian** [comment]
Should be fixed, see the releases tab, or go to cpan later tonight
