### ISSUE TITLE
support for text() using find_element or find_child_element?

### ISSUE THREAD

**Issue by CJohnno77** [teodesian/Selenium-Remote-Driver#475]
Just wondering if I have a "text()" in my xpath query, how can I do this using find_element or find_child_element?

Currently when I do this:

`@spantext = $selen->find_child_element($mat_tree_node,'span/button/span/text()');`

I get this error:

`TypeError: node.ownerDocument is null`

**Comment by teodesian** [comment]
Selenium won't return shadow DOM nodes like TextNodes from selectors.  You instead should get the element which wraps the textNode and call getText.

Get the element you want first, then call get_text() on the webElement returned.
https://metacpan.org/pod/Selenium::Remote::WebElement#get_text

Simpler example:
```
my $span = $mat_tree_node->child('span/button/span');
my $text = $span->get_text();
```

**Comment by CJohnno77** [comment]
The problem is that [get_text()](url) on the element will get the text of all child nodes as well.  I want just the element's text (no child nodes), and `text()` seems to be the only way to do that.

**Comment by teodesian** [comment]
what is stopping you from using a more specific selector to get only the child you specifically want the text from?

**Comment by CJohnno77** [comment]
`<div>Hello<span>World</span></div>`

I want only the `<div>` text, not the child `<span>` text as well.  So I want "Hello", not "HelloWorld".

If I do `find_element('//div')->get_text()` it will give me "HelloWorld". I want to be able to do `//div/text()` which in other XPath implementations such as HTML::TreeBuilder::XPath would give me "Hello".

Hope that makes sense.

**Comment by teodesian** [comment]
Selenium's get_text returns the same as the inner_text property would in javascript.  I can't really help that.

What you can do on the other hand is dump the outerHTML for that particular element and run it through TreeBuilder to do what you want.

To get the outerHTML, you would execute_script on the webelement:
```
my $span = $mat_tree_node->child('span/button/span');
my $outerHTML = $span->execute_script('return arguments[0].outerHTML');
```

**Comment by CJohnno77** [comment]
OK, thanks, I did `$span->get_attribute("outerHTML")` and managed it run it through TreeBuilder and got the result I wanted.  The only thing to note is that TreeBuilder wraps `<html><head><body>` around the element so that's something to watch out for.

**Comment by teodesian** [comment]
cool.
