### ISSUE TITLE
Add the constant values to document of Selenium::Remote::WDKeys

### ISSUE THREAD

**Issue by yuki-kimoto** [teodesian/Selenium-Remote-Driver#477]
It seems currently the constant values of Selenium::Remote::WDKeys are not documented.

https://metacpan.org/pod/Selenium::Remote::WDKeys

Can I add these constant values to the document?

**Comment by teodesian** [comment]
Yes, please do.

It's a shame there isn't a Pod::Weaver::Section::Constant plugin to make this easy.  As such I'll be quite happy with whatever you provide.

**Comment by yuki-kimoto** [comment]
I will create the document in a few weeks.

**Comment by yuki-kimoto** [comment]
I pull request #478.

Please see the changes. If you find the improvement points, I can add them.

**Comment by teodesian** [comment]
Looks good to me.  I'll send up a release sometime tonight.
