### ISSUE TITLE
Documentation refers to "moveto" instead of "move_to"

### ISSUE THREAD

**Issue by richlv** [teodesian/Selenium-Remote-Driver#483]
In https://github.com/teodesian/Selenium-Remote-Driver/blob/master/lib/Selenium/Remote/Driver.pm , multiple places refer to "moveto". Searching for that doesn't help much though, as the method (alias) is "move_to".
Perhaps the "moveto" references should also include underscore and talk about "move_to"?

**Comment by teodesian** [comment]
Thanks for the report.  moveto refers to the underlying selenium command name, which is generally what we think of as implementors here.
